### ISSUE TITLE
Very slow message delivery in some cases with Fast-RTPS 1.9.x [8914]

### ISSUE THREAD

**Issue by clalancette** [eProsima/Fast-DDS#1120]
## Expected Behavior
There is an example ROS 2 workload at https://gist.github.com/clalancette/cdd5082838c38da94923ed8ba16d1342 .  When compiling and running that workload (exact steps below), we expect that a trigger on one end of the pipeline will result in a pointcloud being published at the other end of the pipeline in < 500 ms.

## Current Behavior
It can take anywhere from 500 ms up to 30 seconds for the pipeline to complete.  Sometimes, the pipeline never completes at all (this happens more as more load is being placed on the machine).

## Steps to Reproduce
1.  Setup machine for ROS 2: https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Development-Setup/
1.  mkdir -p pc_pipe_full_ws/src
1.  cd pc_pipe_full_ws
1.  wget https://gist.githubusercontent.com/clalancette/cdd5082838c38da94923ed8ba16d1342/raw/8670ceb1e201822f0d5d56a52f45982c5c3739b1/pc_pipe_full.repos
1.  vcs import src < pc_pipe_full.repos
1.  colcon build  # This will take a while

Terminal 1:
1.  source pc_pipe_full_ws/install/setup.bash
1.  ros2 launch pc_pipe bringup.launch.xml start_gazebo:=true viz:=true

Terminal 2:
1.  source pc_pipe_full_ws/install/setup.bash
1.  ros2 topic echo --qos-reliability reliable --no-arr /mycamera/points2

Terminal 3:
1.  source pc_pipe_full_ws/install/setup.bash
1.  ros2 topic pub -1 mycamera/image_trigger std_msgs/msg/Empty

When that last command is run, the pipeline is kicked once.  A bunch of timing information is written to /tmp/pc_pipe_times.csv.  If you download https://gist.github.com/clalancette/dfaee6948105bd1f781bbf151dc60a3c, that script does some basic analysis on the output.  You can run it like: `python3 parse_pc_pipe_times.py /tmp/pc_pipe_times.csv`

## System information

- Fast-RTPS version: 1.9.x branch, hash e72b1c3c380affd177bf427072c0fe74b9d874d2
- OS: Ubuntu 18.04
- Network interfaces: lo, eth0 (whatever Fast-RTPS chooses as default)
- ROS2: Foxy pre-release.

## Additional context

The pipeline goes like this:

```
trigger -> camera_controller (running inside gazebo) -> image_filter_right  -> disparity_node -> point_cloud_node -> topic echo
                                                                                 ^
                                                     -> image_filter_left -------|
```

Looking at some of the worst offenders in practice, it looks like this:

```
Maximum total time (ms): 27192
  start -> camera_controller: 1 ms
  camera_controller -> image_filter: 63 ms
  image_filter -> disparity: 9045 ms
  disparity -> pointcloud sub: 13 ms
  pointcloud sub -> pointcloud pub: 33 ms
  pointcloud pub -> ros2topic echo: 18037 ms
```

There's probably some delays in Gazebo, and there also maybe some delay in using the ROS 2 image_filter in the disparity node.  But the time from the pointcloud pub to ros2topic echo is a simple publication, so the fact that it takes 18 seconds sometimes makes me thinks there is something going on in the network.

Please let me know if you need any additional information.

**Comment by lukicdarkoo** [comment]
What is the size of your point cloud messages? We may have a similar issue (#1107)

**Comment by clalancette** [comment]
Our pointcloud messages are about 9MB.

**Comment by dirk-thomas** [comment]
@MiguelCompany Is there any update on this ticket?

**Comment by lukicdarkoo** [comment]
> Our pointcloud messages are about 9MB.

Messages bigger than 65Kb are fragmented (section 9.6 [here](https://readthedocs.org/projects/eprosima-fast-rtps/downloads/pdf/latest/)). Therefore, in your case, it sends around 140 fragments per message. This looks like a cause of the problem.

**Comment by dirk-thomas** [comment]
> it sends around 140 fragments per message. This looks like a cause of the problem.

I highly doubt that this can cause delays of up to 30 seconds.

**Comment by MiguelCompany** [comment]
Depending on the size of the socket buffers (both sending and receiving ones), several fragments may be lost. 

I do agree that 18 seconds is too high for a single publication, and it seems related to #1107 and #1062 

I do have seen improvement with #1190, and the results (at least on my machine) are different depending on the Linux version. I cannot reproduce #1062 on Focal, but I do see problems on 18.04.

While we investigate where the high CPU usage comes from, I see two possible workarounds for this:
* Increase socket buffers (either with `sysctl` or on the [Participant XML profile](https://fast-rtps.docs.eprosima.com/en/latest/xmlprofiles.html#participant-profiles) - attributes `sendSocketBufferSize` and `listenSocketBufferSize`)
* Set a [flow controller](https://fast-rtps.docs.eprosima.com/en/latest/xmlprofiles.html#throughput) so that fragments are sent separately.

**Comment by MiguelCompany** [comment]
@clalancette Did you try any of the workarounds I proposed on my previous comment?

**Comment by MiguelCompany** [comment]
We have made several improvements for branch 2.0.x, the last of them is on PR #1209. We have seen big improvements on issue #1062 which, as this issue, is related to big data and ROS2 Foxy.

@clalancette @dirk-thomas Could you check on your side?

**Comment by lukicdarkoo** [comment]
@MiguelCompany I have just tested with FastRTPS from 2.0.x branch and ROS2 Eloquent on my PC.

Here is the example:
```python
import rclpy
from rclpy.node import Node
from std_msgs.msg import Int8MultiArray


MESSAGE_N_BYTES = int(1e6)
PUBLISH_PERIOD = 0.1


class TestPublisher(Node):
    def __init__(self):
        super().__init__('test_publisher')
        self.publisher = self.create_publisher(Int8MultiArray, 'test', 10)
        self.timer = self.create_timer(PUBLISH_PERIOD, self.timer_callback)

    def timer_callback(self):
        msg = Int8MultiArray()
        msg.data = [0] * MESSAGE_N_BYTES
        self.publisher.publish(msg)


def main(args=None):
    rclpy.init(args=args)
    test_publisher = TestPublisher()
    rclpy.spin(test_publisher)
    test_publisher.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
```

And the result:
```
$ ros2 topic hz /test
average rate: 4.402
	min: 0.195s max: 0.384s std dev: 0.07015s window: 6
average rate: 4.768
	min: 0.189s max: 0.384s std dev: 0.05259s window: 12
average rate: 4.878
	min: 0.189s max: 0.384s std dev: 0.04349s window: 18
```
As you can see, instead of 10 messages per second I am receiving around 5. But even worse, CPU usage on my PC is 100% (of a single core).

With smaller messages, e.g. `MESSAGE_N_BYTES = int(1e3)` (1KB) and `PUBLISH_PERIOD = 1e-3` (1KHz) I receive messages at 1KHz and CPU usage is way lower than 100%.

**Comment by clalancette** [comment]
Sorry for the delay in responding here.  I spent some time today to try and get more information.

To start with, I'm using Fast-DDS commit d5718a114337cb85987b0b4539cbd7aea1f643d2 .  The setup is largely the same as described in the initial comment, with the exception that all publishers and subscribers are now RELIABLE.  This is to ensure that we always get message delivery with high fragmentation.  Otherwise, the graph is the same as in the initial comment.

With the latest code, things are much improved.  Whereas in the initial comment I was getting up to 27 seconds between publishes, the worst case I am now seeing is 6 seconds between publishes:

```
Total complete pipeline passes: 737
Average total time (ms): 463
Median total time (ms): 135
Minimum total time (ms): 106
Maximum total time (ms): 6141
  start -> camera_controller: 0 ms
  camera_controller -> image_filter: 34 ms
  image_filter -> disparity: 6047 ms
  disparity -> pointcloud sub: 12 ms
  pointcloud sub -> pointcloud pub: 22 ms
  pointcloud pub -> ros2topic echo: 26 ms
```

You can also see that the median is quite good, though the average is not.  Qualitatively, it seems like the behavior is very bursty.  I'll get a few pointclouds via the pipeline in a row, and then the whole thing will "stall" for several seconds.  After the stall, it then publishes a few more pointclouds.

I have not yet tried increasing the socket buffers or the flow controller; if you think that is worthwhile, I can give that a try as well.

**Comment by MiguelCompany** [comment]
@clalancette 

> I have not yet tried increasing the socket buffers or the flow controller; if you think that is worthwhile, I can give that a try as well.

Please do. Either using a flow controller or increasing the socket buffers should help mitigating fragment loss.

Regarding bursty behavior: as you are using reliable, the subscriber will keep new data in the history while old data is being reassembled. This means that if some fragments are lost, it is likely that you will be notified of several samples at the same time.

**Comment by EduPonz** [comment]
Hi @clalancette ,

We have been trying to reproduce your test case to speed up the support. Unfortunately, we are having little success. We hope you can give us a hand!

We are using your `pc_pipe_full.repos` and following the instructions you kindly outlined in your [description of the issue](https://github.com/eProsima/Fast-DDS/issues/1120#issue-592125537). However, we are having much trouble building the workspace (we've tried in Ubuntu 20.04 and also in two different Ubuntu 18.04). The problems vary in form, but in the end it all boils down to incompatibilities between the package versions. I believe this happens because most of the packages in the `.repos` file are obtained from the master branches, which have probably changed quite a bit since you put your workspace together. It'd be really helpful if you could send us the hashes of all the packages in your workspaces, so we can precisely reproduce your scenario. Luckily, `vcs` allows you to export your workspace as a `.repos` file with hash versions with the following command:

```
vcs export --exact src > pc_pipe_full_hash.repos
```

Thanks in advance for your help!

**Comment by EduPonz** [comment]
Hi @clalancette 

Did you have a chance to look at the answer? We would very much like to verify whether the performance has improved since your last tests.

Thanks!

**Comment by clalancette** [comment]
Things improved a lot between 1.9.x and 2.1.x.  Unfortunately, I'm probably not going to work on this particular issue in the near future, so I'm going to go ahead and close this out.  If we run across a similar situation in the future, I'll go ahead and open a new issue.
