### ISSUE TITLE
[Question] Can Fast-RTPS be used to transmit data between devices with intermitent connection [9147]

### ISSUE THREAD

**Issue by msmcconnell** [eProsima/Fast-DDS#1219]
I am investigating whether DDS/Fast-RTPS can be used in situations where IoT devices need to share local data with each other. Consider the situation below:
Imagine I have two IoT devices which can move (a cell phone, car, drone, etc.). These devices need to share data about their local environment with other devices near by. To reduce delivery time, this data is shared using local broadcast communications such as Bluetooth or radio transmission. In other words the data is not going over a cellular data connection like 4G. 

For example you could have a situation like this where no device sees another.
<img src="https://user-images.githubusercontent.com/10292079/82373602-cd5cd980-99eb-11ea-976d-5701fc4d6492.png" width="250" height="250">

But later on they could interact:
<img src="https://user-images.githubusercontent.com/10292079/82374272-ce423b00-99ec-11ea-8a3a-19ebe9a6a1a0.png" width="250" height="150">

So, new data transmission on topics would only occur in the second image. 
Based on the documentation, it seems to me that this could be done using a new transport layer and using a Durability of Volatile. However, I am not sure if this is something DDS is really designed to support. Would this be practical or would it make more sense to just use more traditional broadcast communication protocols and reserve DDS for internal or internet based communications?

**Comment by EduPonz** [comment]
Hi @msmcconnell ,

I'm afraid the answer is both yes and no. On the one hand, Fast DDS does support scenarios where the connection comes and goes, since the discovery of peers is dynamic and it's attempted periodically. On the other hand, Fast DDS does not support Bluetooth or Radio transports. Currently, Fast DDS supports the following types of communication:

* UDPv4/6
* TCPv4/6
* Shared memory
* Intra-process

Regarding Durability (and any other QoS settings), the appropriate configuration really much depends on the requirements of the system.

**Comment by EduPonz** [comment]
I'm going to go ahead and close the issue for now as the question has been answered. Please feel free to comment or reopen at any time.
