### ISSUE TITLE
wget fails on eprosima.com: Unable to establish SSL connection

### ISSUE THREAD

**Issue by dayjaby** [eProsima/Fast-DDS#1224]
On a fresh Ubuntu 20.04 installation, I tried to get the tar.gz from eprosima.com, but the SSL connection fails. In thew new openssl version, the default security level got raised to 2 (OPENSSL_TLS_SECURITY_LEVEL=2), which appears to be the cause.

## Steps to Reproduce
1. Install Ubuntu 20.04
2. `$ wget https://www.eprosima.com/index.php/component/ars/repository/eprosima-fast-rtps/eprosima-fast-rtps-1-7-1/eprosima_fastrtps-1-7-1-linux-tar-gz`
```
--2020-05-22 05:05:12--  https://www.eprosima.com/index.php/component/ars/repository/eprosima-fast-rtps/eprosima-fast-rtps-1-7-1/eprosima_fastrtps-1-7-1-linux-tar-gz
Resolving www.eprosima.com (www.eprosima.com)... 80.231.171.97
Connecting to www.eprosima.com (www.eprosima.com)|80.231.171.97|:443... connected.
OpenSSL: error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type
Unable to establish SSL connection.
```

## System information

```
$ openssl version -a
OpenSSL 1.1.1f  31 Mar 2020
built on: Mon Apr 20 11:53:50 2020 UTC
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-P_ODHM/openssl-1.1.1f=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
Seeding source: os-specific
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

**Comment by EduPonz** [comment]
Hi @dayjaby ,

We are in contact with our server manager to get this fixed. In the mean time, it is possible to downloads all eProsima products from https://www.eprosima.com/index.php/downloads-all.

Furthermore, I'm sending you some related links and a temporal workaround, in case it helps:

1. https://github.com/linkchecker/linkchecker/issues/188
1. https://github.com/openssl/openssl/issues/7126
1. https://stackoverflow.com/questions/58342699/php-curl-curl-error-35-error1414d172ssl-routinestls12-check-peer-sigalgwr

I'm closing the issue since it is more an eProsima webpage issue and not really related with Fast DDS project. In any case, feel free to reopen or comment at any time.

**Comment by EduPonz** [comment]
Hi @dayjaby ,

We'd like to know what is your use case so we can offer you better support. Do you have some sort of automated build process which includes downloading Fast DDS installer? We'll be happy to help you sorting it out in the best possible manner.
