### ISSUE TITLE
Question: How to get transport details of Domain Participant?

### ISSUE THREAD

**Issue by anamud** [eProsima/Fast-DDS#1271]
Hi,

I am using Fast-DDS 2.0.0.

I understand that one can specify a custom transport descriptor while creating a participant. This is nicely exemplified in the UserDefinedTransportExample application.

I would like to understand if it is possible to programmatically get transport details after the participant has been created. There are two cases here: the participant was created using the builtin transport or was created using a custom transport. 

I am particularly interested in knowing the interfaceWhiteList and m_output_udp_socket parameters of the UDPv4 transport descriptor.

If this is not possible today, do you foresee design-level challenges to implement such a feature?

**Comment by anamud** [comment]
I was able to get `interfaceWhiteList` and `m_output_udp_socket` parameters using the `getAttributes` interface of the `Participant` class when a custom transport is used. Is there a possibility to get the same parameters when builtin transport is used (assuming `interfaceWhiteList` contains the default interface) ?

**Comment by rsanchez15** [comment]
Hi @anamud,

First of all I want to clarify the use of the `interfaceWhiteList` in Fast DDS. The `interfaceWhiteList` is a mechanism to force the use of several network interfaces, that is, the user defines a list of network interfaces in the `TransportDescriptor` that will be used by the DomainParticipant setting that `TransportDescriptor`. This avoids the use of any other network interface available on the machine.
You can find more information about the use of the `interfaceWhiteList` in Fast DDS [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/whitelist.html).
As for the `m_output_udp_socket` parameter you mention, I'm afraid it's not possible to access it since the builtin transports don't build an `UDPTransportDescriptor`, so this parameter is unreachable. 
The approach you can consider is to define an UDP transport in which the parameters you consider are defined. [Here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/udp/udp.html) you can find a description of the UDP transport settings in Fast DDS as well as an example of its implementation.

**Comment by rsanchez15** [comment]
I am closing this issue since the question has been resolved. In case the answer is not clear you can always reopen the issue, or create new ones for any questions you may have.
