### ISSUE TITLE
IDL compiler generated files in the repository? [9125]

### ISSUE THREAD

**Issue by jwillemsen** [eProsima/Fast-DDS#1280]
Why are all IDL compiler generated files part of the various examples under https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B? At the moment a change is made to the code generation (I do have suggestions when looking at some generated files) these files all need to be regenerated, why are they not generated part of the compile step?

**Comment by jwillemsen** [comment]
See #1284 for some suggestions I have, with all IDL files in the repo it looks to be hard to experiment with the code generation

**Comment by jparisu** [comment]
We have decided that Fast-DDS-GEN library would not be a requirement in Fast-DDS compilation, as it is not needed in some cases.

Following your advice, we have re-generate all the type_support files for the examples in RTPS & DDS directories, so the default file from Fast-DDS-GEN is used following the .idl file.

Unluckily, we cannot fulfill your request of eliminating the type files and regenerating them during the compilation because of the library requirements issue.
Nevertheless, we can provide you with an easy and fast python3 script that would re-generate those files in a particular example or in all of them, in order to make the compilation easier when modifying the .idl files.
I could provide this script via email if you want it (python files are not supported in github comment attachments).

**Comment by jwillemsen** [comment]
Why not put the script in the git archive and add a github action that triggers this script and checks that there are no differences between the files in the archive after the script has been executed. That would make sure the generated files are kept up to date.

**Comment by jparisu** [comment]
> Why not put the script in the git archive and add a github action that triggers this script and checks that there are no differences between the files in the archive after the script has been executed. That would make sure the generated files are kept up to date.

Sure this would be a great aspect for the project, but there is still the problem that we do not want Fast-DDS-GEN to be a requirement in Fast-DDS library compilation.

Also we find other design issues to add this feature as:
- python3 is not a requirement for the library.
- The different examples from Fast-RTPS and Fast-DDS need different versions of Fast-DDS-GEN in order to use DDS or RTPS library.
- We do not want to add scripts for auxiliary functionalities external to the library in the repository.
- The examples are focused on showing the user how to use Fast-DDS, and not on helping with the use of Fast-DDS-GEN and understanding type_supports.

If you are interested in using such script, I could provide it to you via email.
