### ISSUE TITLE
incorrectly added -lrt library when building for QNX [8998]

### ISSUE THREAD

**Issue by amdsobhy** [eProsima/Fast-DDS#1309]
in https://github.com/eProsima/Fast-DDS/blob/master/cmake/modules/FindThirdpartyBoost.cmake, line 16

- add:
if(WIN32 OR APPLE OR QNX)

FastRTPS:
commit 40568fa (HEAD -> 2.0.x, tag: v2.0.1, origin/2.0.x)

**Comment by jwillemsen** [comment]
Maybe open a pull request so that this can be more easily integrated?

**Comment by MiguelCompany** [comment]
> Maybe open a pull request so that this can be more easily integrated?

@amdsobhy I second this. Please open a pull request with the suggested change.

**Comment by asobhy-qnx** [comment]
will do

**Comment by pablorcum** [comment]
This is still failing for QNX Neutrino. CMake OS flag as of today (see [here](https://github.com/Kitware/CMake/blob/master/Modules/Platform/QNX.cmake)) is QNXNTO instead of QNX. Please add:
`if(WIN32 OR APPLE OR QNX OR QNXNTO)`

**Comment by asobhy-qnx** [comment]
Hi @pablorcum, you need to add this in your toolchain file 
set(QNX TRUE)
set(CMAKE_SYSTEM_NAME QNX)

You can take a look at the toolchain file here https://github.com/asobhy-qnx/bullet3/blob/master/qnx.nto.toolchain.cmake as a reference.

**Comment by pablorcum** [comment]
Thank you, @asobhy-qnx. That's right, I had added `set(QNX 1)` to my QNX toolchain file, which had already `set(CMAKE_SYSTEM_NAME QNX)`, and it works. But it is a workaround.

CMake already adds automatically `set(QNXNTO 1)` if it detects crosscompiling to QNX as shown [here](https://github.com/Kitware/CMake/blob/master/Modules/Platform/QNX.cmake). No need to add any environment variable in the toolchain file. Therefore, and to be compliant to CMake documentation and so that it works off-the-shelf, QNXNTO should be added to FindThirdpartyBoost.cmake.

**Comment by asobhy-qnx** [comment]
Thank you for the clarification. It does seem like the better way to do it. I would like to test it then maybe change it to QNXNTO instead

**Comment by asobhy-qnx** [comment]
@pablorcum  https://github.com/eProsima/Fast-DDS/pull/1456 & https://github.com/eProsima/Fast-DDS/pull/1455
