### ISSUE TITLE
Bypass CDR serializer [9156]

### ISSUE THREAD

**Issue by lbrunet1982** [eProsima/Fast-DDS#1353]
Is it possible to use FastDDS with protobuffers or another serialization library and bypass the CDR encoding mechanism?  Right now I have a dummy IDL message with a single string parameter that I copy a protobuffer encoded message into.  I then publish that message where it gets encoded internally again before being sent, but it would be handy to bypass this step since the message is already encoded.

Thanks!

**Comment by EduPonz** [comment]
Hi @lbrunet1982 ,

Fast DDS is agnostic of the serialization that applications want to implement. This means that Fast DDS only needs to know about a "Type Support" object that can perform certain operations, mainly:
* serialize
* deserialize
* get key
* create data
* delete data

This type support can be any class deriving from `eprosima::fastrtps::TopicDataType` that overloads all the virtual methods, namely:
```c++
bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload);
bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data);
std::function<uint32_t()> getSerializedSizeProvider(void* data);
bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5);
void* createData();
void deleteData(void * data);
```

As long as your class inherits from `eprosima::fastrtps::TopicDataType`  and defines that interface, you are good to go.

For the task of converting an IDL into C++, we provide another package [Fast DDS-Gen](https://github.com/eProsima/Fast-DDS-Gen) that generates this type support class (naming the files "<type_name>PubSubTypes.h/cxx"), plus an auxiliary class (files named "<type_name>.h/cxx") that provides some utilities to the user to manage the type. That generated code uses [Fast CDR](https://github.com/eProsima/Fast-CDR) for managing the serialization. However, your implementation of the type support does not require that second auxiliary class, since the only thing Fast DDS know about is the type support ("*PubSubTypes.h/cxx"). Fast DDS does not know anything about the serialization mechanism, since that is handled by the type support.

I'll go ahead and close the issue for know as the question has been answered. However, feel free to reopen comment or reopen at any time if you need further information.
