### ISSUE TITLE
[Question] DF('Don't fragment') flag on dds communication [9158]

### ISSUE THREAD

**Issue by condor21** [eProsima/Fast-DDS#1358]
Hi, 

Currently I am working on ROS2 nodes development jobs, and encounter a necessity to send a unfragmented udp packet through DDS channel. 

Therefore, I would like to know whether it is possible to turn on the 'DF('Don't fragment')' flag on the fastDDS layer to avoid IP fragmentation. 

If it is not a proper place to ask a such question, I will remove or move this post. Thanks in advance for any help.

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @condor21,

Fast DDS does not allow you to set the DF ('Don't Fragment') flag on the UDP transport. However, if you know your network topology, you can set both buffer sizes (`sendBufferSize` and `receiveBufferSize`) to the minimum MTU present in your network in order to prevent the fragmentation of the data.

Besides defining your TransportDescriptor configuring the options for your desired transport, you must add this TransportDescriptor to the user_transports vector in the TransportConfigQoS policy. Additionally, if you want to use only your customize transport, you should also remember to disable the built-in transport layer by setting the TransportConfigQoS flag `use_builtin_transports` to false (more information in the Fast DDS documentation: [TransportInterface](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/transport_api.html#transportinterface))

**Comment by JLBuenoLopez-eProsima** [comment]
'll go ahead and close the issue considering the question to have been answered. However, feel free to comment or reopen at any time if you need further information.
