### ISSUE TITLE
[RTPS_TRANSPORT_SHM Error] Failed to create segment [10057]

### ISSUE THREAD

**Issue by alsora** [eProsima/Fast-DDS#1606]
Hi, I'm running ROS 2 with FastDDS on an embedded device.
I'm using the default version that ships with ROS 2 foxy.

Whenever I run an application I get the following error.
It looks more a warning than an error, as then everything still works as expected.

```
2020-11-27 12:58:53.966 [RTPS_TRANSPORT_SHM Error] Failed to create segment fastrtps_b2468d3c0628a222: No such file or directory -> Function Segment
2020-11-27 12:58:53.979 [RTPS_MSG_OUT Error] No such file or directory -> Function init
```

I guess that this means that I will not be using shared memory transport.
Do you know what could be causing it?

I would like to make the error disappear for applications that do not require shared memory, but also understand what is the cause as eventually I'm interested in using SHM.

Could the available flash/RAM space on the device cause this? I'm quite tight on these resources.

Thank you

**Comment by MiguelCompany** [comment]
@alsora 

I think this is failing inside the call to `RegisterTransport` on [this line](https://github.com/eProsima/Fast-DDS/blob/e7e96153a52d29e97c5a69a056bbd0cbb090b515/src/cpp/rtps/participant/RTPSParticipantImpl.cpp#L140). Possible reasons include OS permissions (I think this is unlikely) or, as you suspect, exhaustion of the maximum allowed SHM space.

In order to disable or configure the SHM transport, you can use the following XML configuration. Information on how to make Fast DDS use the XML configuration can be found [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/xml_configuration/xml_configuration.html#xml-profiles)

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    
    <transport_descriptors>

        <!-- We still want the default UDP transport to be present -->
        <transport_descriptor>
            <transport_id>udp_transport</transport_id>
            <type>UDPv4</type>
        </transport_descriptor>
    
        <!-- We want a customized version of the SHM transport -->
        <transport_descriptor>
            <transport_id>shm_transport</transport_id>
            <type>SHM</type>
            
            <!--
                Configure the size in bytes of the shared memory segment.
                On a Linux based system, you can get the maximum allowed value with
                    $ sysctl -a | grep shmmax
            -->
            <segment_size>65536</segment_size>
            
            <!--
                The following value should be lower than or equal to segment_size.
                The default value is shown here.
            -->
            <maxMessageSize>65500</maxMessageSize>
        </transport_descriptor>

    </transport_descriptors>

    <participant profile_name="CustomParticipant"  is_default_profile="true">
        <rtps>
            <!--
                As customized versions of the default transports are used, the
                built-in ones should be disabled
            -->
            <useBuiltinTransports>false</useBuiltinTransports>

            <!-- Link the Transport Layer to the Participant -->
            <userTransports>
                <transport_id>udp_transport</transport_id>

                <!-- Comment the following line in order to disable the SHM transport -->
                <transport_id>shm_transport</transport_id>
            </userTransports>
        </rtps>
    </participant>
</profiles>
```

**Comment by alsora** [comment]
Thank you for the explanation.

This is the maximum allowed shared memory segment on my system
```
$ sysctl -a | grep shmmax
kernel.shmmax = 4278190079
```

If I create an XML file where I only use UDP transport, then the error disappears.
If I use your XML file (with both UDP and SHM) I still get the error, no matter what segment size value I set.

```
2020-11-30 11:47:47.065 [RTPS_TRANSPORT_SHM Error] Failed to create segment fastrtps_e5983eeac2120177: No such file or directory -> Function Segment
2020-11-30 11:47:47.154 [RTPS_MSG_OUT Error] No such file or directory -> Function init
2020-11-30 11:47:47.156 [RTPS_PARTICIPANT Error] Unable to Register SHM Transport. SHM Transport is not supported in the current platform. -> Function RTPSParticipantImpl
```

The last error comes from [here](https://github.com/eProsima/Fast-DDS/blob/cea3509ddc122dffc673e3fc3d24fcc8d4870ebd/src/cpp/rtps/participant/RTPSParticipantImpl.cpp#L185-L190).
It assumes that the transport has not been registered because not supported but I think that any failure in the registration function can lead to that.

**Comment by MiguelCompany** [comment]
@alsora Let's check permissions then. The typical implementation of shared memory on Linux relies on a `tmpfs` mounted on `/dev/shm`

Does this folder exist on your system? Can the user under which your Fast DDS application runs create a file there?

**Comment by MiguelCompany** [comment]
@alsora Could you apply the following patch to Fast DDS and check again? This will give us more information on the reason for the error.

```diff
diff --git a/src/cpp/rtps/transport/shared_mem/SharedMemSegment.hpp b/src/cpp/rtps/transport/shared_mem/SharedMemSegment.hpp
index b26525d69..449fda640 100644
--- a/src/cpp/rtps/transport/shared_mem/SharedMemSegment.hpp
+++ b/src/cpp/rtps/transport/shared_mem/SharedMemSegment.hpp
@@ -179,11 +179,16 @@ public:
             return extra_size;
 
         }
+        catch (const boost::interprocess::interprocess_exception& e)
+        {
+            logError(RTPS_TRANSPORT_SHM, "Failed to create segment " << uuid.to_string()
+                << ": " << e.what() << " (" << e.get_error_code() << ", " << e.get_native_error() << ")");
+            throw;
+        }
         catch (const std::exception& e)
         {
             logError(RTPS_TRANSPORT_SHM, "Failed to create segment " << uuid.to_string()
                                                                      << ": " << e.what());
             throw;
         }
     }

```

**Comment by wangzhensuo** [comment]
i found that ,once this error occured , if i run HelloWorldExample  .  it also occured same error. if i restart PC ,and run HelloWorldExample again, it could run ok.  I don't know why.

**Comment by piaopiaohu123** [comment]
@wangzhensuo  when i build ROS2 on android, i meet the same problem, maybe we need add QNX.hpp or android,hpp for boost repo, you it can build with the macro chosed by envriment.   and another way is restart all the build method, refer to:https: [//ros2-qnx-documentation.readthedocs.io/en/latest/build_from_source.html ](url)

**Comment by JLBuenoLopez-eProsima** [comment]
Sorry @alsora 

I am going to close this issue due to inactivity. Last year a [patch was provided](https://github.com/eProsima/Fast-DDS/issues/1606#issuecomment-749971814) to obtain more information about the issue. No feedback has been received since then. Feel free to reopen the issue providing the required information.

**Comment by Aposhian** [comment]
This may be related to #2790. `sysctl -a | grep shmmax` gives you the max _allowed_ size, but doesn't tell you how much space _is actually available_. You can see that with
```
$ df -Th | grep '/dev/shm\|Used'
Filesystem     Type      Size  Used Avail Use% Mounted on
tmpfs          tmpfs      32G  2.4G   29G   8% /dev/shm
```

**Comment by Mario-DL** [comment]
Hi @SteveMacenski 
It would be nice if you could provide some more information on the context
Could you confirm the platform in which you are running the image ? 
Are you using special arguments for starting the container ?
Also, does the error happen every time ?

**Comment by SteveMacenski** [comment]
More context is here with reproduction instructions: https://github.com/ros-navigation/navigation2/pull/4298#issuecomment-2121319831

Its showing up in all of our test logs on the Jazzy 24.04 Docker container just compiling and running Nav2 with no changes to Fast-DDS / RMW configs or anything special / custom. Yes, it happens every time and as far as I can tell every time we run ROS 2 with Fast-DDS RMW.

**Comment by Mario-DL** [comment]
Hi @SteveMacenski 
I have been trying to reproduce the issue. It did not happen every time, in fact it was hard to reproduce the first time.
I observed that the error is triggered when the `/dev/shm/` container's volume gets to its maximum capacity (see the attached image). The error starts triggering starting from that moment.

![error](https://github.com/eProsima/Fast-DDS/assets/116071334/5c3f9441-00b1-4ebb-ab78-83ab1b7d7f75)

The cause is that the memory segments created in `/dev/shm` are not being correctly cleaned. I read in the PR you link that there are issues terminating some tests and I think that it the root cause. Between two test runs I observed that the directory usage increases a 10~15 percent each time. So, If the tests are run many times, the directory would get full at some point, thats my initial guess.
Something that could help would be launching the dev container adding the `--shm-size=Xmb` argument. Or cleaning up the `/dev/shm` between runs.
Please let us know if that helps.

**Comment by SteveMacenski** [comment]
I see this deterministically every time on my computer: 13th Gen Intel® Core™ i7-1365U × 12 running Ubuntu 22.04 with the instructions in the comment (24.04/Jazzy Docker).  I saw this for all failed tests, but I expect that it is always happening and I'm only seeing the logs of the failed tests from `colcon test-result --verbose` to tell. I just checked some successful tests in the logs and it is indeed happening every time from the 5 files I randomly sampled. Example: 

```
					<Value>-- run_test.py: invoking following command in '/jazzy_ws/build/nav2_util/test':
 - /jazzy_ws/build/nav2_util/test/test_lifecycle_utils --gtest_output=xml:/jazzy_ws/build/nav2_util/test_results/nav2_util/test_lifecycle_utils.gtest.xml
Running main() from /opt/ros/jazzy/src/gtest_vendor/src/gtest_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Lifecycle
[ RUN      ] Lifecycle.interface
[NON-XML-CHAR-0x1B][37;1m2024-05-21 23:19:14.907 [NON-XML-CHAR-0x1B][31;1m[[NON-XML-CHAR-0x1B][37;1mRTPS_TRANSPORT_SHM[NON-XML-CHAR-0x1B][31;1m Error] [NON-XML-CHAR-0x1B][37mFailed to create segment 9b177afabb4e750b: boost::interprocess_exception::library_error[NON-XML-CHAR-0x1B][34;1m -&gt; Function [NON-XML-CHAR-0x1B][36mcompute_per_allocation_extra_size[NON-XML-CHAR-0x1B][m
[NON-XML-CHAR-0x1B][37;1m2024-05-21 23:19:14.908 [NON-XML-CHAR-0x1B][31;1m[[NON-XML-CHAR-0x1B][37;1mRTPS_TRANSPORT_SHM[NON-XML-CHAR-0x1B][31;1m Error] [NON-XML-CHAR-0x1B][37mFailed to create Shared Memory Manager for domain fastrtps: boost::interprocess_exception::library_error[NON-XML-CHAR-0x1B][34;1m -&gt; Function [NON-XML-CHAR-0x1B][36mcreate[NON-XML-CHAR-0x1B][m
[NON-XML-CHAR-0x1B][37;1m2024-05-21 23:19:14.908 [NON-XML-CHAR-0x1B][31;1m[[NON-XML-CHAR-0x1B][37;1mRTPS_PARTICIPANT[NON-XML-CHAR-0x1B][31;1m Error] [NON-XML-CHAR-0x1B][37mUnable to Register SHM Transport. SHM Transport is not supported in the current platform.[NON-XML-CHAR-0x1B][34;1m -&gt; Function [NON-XML-CHAR-0x1B][36mRTPSParticipantImpl[NON-XML-CHAR-0x1B][m
[       OK ] Lifecycle.interface (34 ms)
[----------] 1 test from Lifecycle (34 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (34 ms total)
[  PASSED  ] 1 test.
-- run_test.py: return code 0
-- run_test.py: inject classname prefix into gtest result file '/jazzy_ws/build/nav2_util/test_results/nav2_util/test_lifecycle_utils.gtest.xml'
-- run_test.py: verify result file '/jazzy_ws/build/nav2_util/test_results/nav2_util/test_lifecycle_utils.gtest.xml'
</Value>
```

But perhaps that's here nor there. Just letting you know that its not from the failed tests, this happens when the tests pass too.

>  Something that could help would be launching the dev container adding the --shm-size=Xmb argument. Or cleaning up the /dev/shm between runs.

Will do. I have things in a bit of a sensitive state right now while debugging some issues so I can't immediately shutdown and test, but I will do that once I button up the current thing I'm debugging / fixing.

**Comment by SteveMacenski** [comment]
I added in `--shm-size=1000mb`  and agree that I don't see it anymore! Thanks for the answer. I'll add that into my ROS 2 docker development tutorial https://docs.nav2.org/tutorials/docs/docker_dev.html for future reference

**Comment by synaptic** [comment]
Errors resolved by restarting the Docker container.  I found that FastRPS is leaving files when ROS is killed, leaving 59GB in /dev/shm.  However, robot is still spinning.
