### ISSUE TITLE
Use the generated X.509 certificate to report an error [13586]

### ISSUE THREAD

**Issue by yiyibst** [eProsima/Fast-DDS#1621]
when I work at commit id bfb448e19bff253293e8f28ee8c3d3d78d882be2, I use the configure and command in test/certs/ to generate new x.509 certificate. And then I use the new x.509 certificate  on arm ,it report error as follows:
[SECURITY Error] Error validating the local participant -> Function init
[PARTICIPANT Error] Problem creating associated Writer -> Function createPublisher
I have two questions：
1、How can I produce the same certificate as in the example（test/certs/ ）
2、Why is this error reported，and I should to do

**Comment by JLBuenoLopez-eProsima** [comment]
I am going to close this issue due to inactivity. More information is required and no answer has been received in the last month (see [CONTRIBUTING](https://github.com/eProsima/Fast-DDS/blob/master/CONTRIBUTING.md#issues)). Feel free to reopen providing the required information, though opening a new ticket using the issue template is advisable.
