### ISSUE TITLE
Hangs in SharedMemTransport when message occupies all free space in shared segment [10307]

### ISSUE THREAD

**Issue by sfod** [eProsima/Fast-DDS#1666]
Transferring N bytes message might hang for indefinite period when max_message_size = N and segment_size = N.

## Expected Behavior
Transferring should either fail at initialization stage or complete without any delays.

## Current Behavior
The issue appears when a message occupies all or almost all free space in a shared segment, so any additional message (e.g., heartbeat) doesn't fit into shared buffer.
Depending on system load and moon phase transferring of such a message might hang indefinitely.

## Steps to Reproduce
The following steps show how the issue appears.
1. Writer sends the actual message. It enqueues the message into buffer, increments `status.enqueued_count` and so on.
2. Reader wakes up in `SharedMemGlobal::Port::wait_pop` method.
3. Writer sends service message. The actual message occupies all free space in a shared segment, so Writer tries to invalidate buffer with `invalidate_if_not_processing` method. This call succeeds if Reader didn't have time to increment `status.processing_count` yet.
4. Reader executes `dec_enqueued_inc_processing_counts` on a buffer node. But at this time Writer already invalidated buffer.
5. Sleep for ~1 second and go to step 1.

Steps 3 and 4 are a race condition between Writer and Reader.

## System information
- Fast-RTPS version: commit b0e119bafc02fd6761ad5cd7c61872c32a008a61
- OS: Ubuntu 20.04.1 LTS
- Network interfaces: Shared Memory Transport

## Additional context
I see two possible solutions:
1. Library should enforce segment_size to be big enough to fit max_message_size message and any additional service messages.
2. Writer process shouldn't invalidate shared buffer that wasn't processed by Reader yet or should invalidate only after some timeout.
I think the first approach is better as it's much easier.
The second approach might improve other edge cases.

I've added a blackbox test which reproduces the issue on my system. The patch is attached to this report.

## Additional resources

[fast_dds_shm_hangs.patch.txt](https://github.com/eProsima/Fast-DDS/files/5746362/fast_dds_shm_hangs.patch.txt)

**Comment by imontesino** [comment]
Hi @sfod,
  The error, as you pointed out, come from the fact that in the case of a small segment size the writer has to overwrite the segment in a single `send` operation. We cannot enforce the writer to wait for the data to have been processed as that a behavior governed by the QoS policies. ([ReliabilityQosPolicyKind](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/standardQosPolicies.html?highlight=reliability#reliabilityqospolicykind), [DurabilityServiceQosPolicy](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/standardQosPolicies.html?highlight=reliability#reliabilityqospolicykind),...).
  In your case since the [ReliabilityQosPolicyKind](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/standardQosPolicies.html?highlight=reliability#reliabilityqospolicykind) is set to `RELIABLE`  it will keep trying to send the data until the reader catches the first buffer before it is overwritten.
  It is up to the user to decide what trade-offs to make with respect to those configurations. To help in this matter we have added a `logWarning` when the writer overwrites the buffer stating that segment size may be too low. We will also add a note in the [documentation](https://fast-dds.docs.eprosima.com/en/latest/).

**Comment by rsanchez15** [comment]
Hi @sfod,
 
Since this issue has already been addressed and resolved, and due to the inactivity in the conversation, the issue is closed. In case another question related to this issue arises again, you can either reopen the issue or create a new one in case the subject is different.
