### ISSUE TITLE
Unable to compile examples when building from source using Colcon [10203]

### ISSUE THREAD

**Issue by HLATAFAT** [eProsima/Fast-DDS#1667]
## Expected Behavior

When I install Fast-Dds from binaries, I could link libraries in Qt creator from "x64Win64VS2015" directory which contains these libs: fastrtps-2.0.lib, fastcdr-1.0.lib, libfastrtpsd-2.0.lib, libfastcdrd-1.0.lib, libfastrtps-2.0.lib, libfastcdrd-1.0.lib 
In this case, examples compile and work just fine. 

## Current Behavior

But when I build Fast-Dds from source using the  Colcon as described in documentation, it only generates two libraries: 
fastcdr-1.0.lib (In \install\fastcdr\lib) and fastrtps-2.1.lib (In \install\fastrtps\lib)
Adding these 2 libs to the project and compiling fails due to the linker error: 
LNK1104: cannot open file 'libfastcdrd-1.0.lib' (in debug)
LNK1104: cannot open file 'libfastcdr-1.0.lib' (in release)

## System information

Windows 10 x64
IDE: Qt creator 5.15.1

**Comment by JLBuenoLopez-eProsima** [comment]
@HLATAFAT,

It seems that Qt is not able to find the libraries. Could you explain how you include those libraries in your project? Also, it is probably a typo, the libraries are generated in the local workspace ([path to the workspace]\install\fastcdr\lib. fastrtps is similar) and are not directly installed globally in the system. You should ensure that Qt includes the path to your local installation folder.

**Comment by HLATAFAT** [comment]
@JLBuenoLopez-eProsima,

I first installed libraries globally using binary installation. Then in the project I linked to them like this (This Works fine):
win32:CONFIG(release, debug|release): LIBS += "C:/Program Files/eProsima/fastrtps 2.0.0/lib/x64Win64VS2017/libfastcdr-1.0.lib"
win32:CONFIG(release, debug|release): LIBS += "C:/Program Files/eProsima/fastrtps 2.0.0/lib/x64Win64VS2017/libfastrtps-2.0.lib"

But when I build from source locally,  It doesn't generate libfastcdr-1.0.lib, libfastrtps-2.0.lib. 
Instead it generates only 2 libraries as below (without the lib prefix):
 [path to the workspace]\install\fastcdr\lib\fastcdr-1.0.lib 
[path to the workspace]\install\fastrtps\lib\fastrtps-2.1.lib

Now when I try to include these in the project as below, it doesn't work (It is looking for libfastcdr-1.0.lib and libfastrtps-2.0.lib):
win32:CONFIG(debug, debug|release): LIBS += "F:\Fast-Dds\install\fastrtps\lib\fastrtps-2.1.lib"
win32:CONFIG(debug, debug|release): LIBS += "F:\Fast-Dds\install\fastcdr\lib\fastcdr-1.0.lib"

**Comment by MiguelBarro** [comment]
@HLATAFAT,

The library fastrtps-2.1.lib is not a static library but is a dll auxiliary that  simply lists all the exported function and variable symbol names that are to be expected from fastrtps-2.1.dll. By default colcon build generates the dynamic libraries. If you want to generate static libraries you must use the cmake variable BUILD_SHARED_LIBS=OFF (modifying the colcon.meta or from the command line using --cmake-args).
The installer is generated calling colcon several times to generate both the dynamic and static libraries. In order to avoid name conflicts the .lib for the dynamic ones have a different name.

**Comment by HLATAFAT** [comment]
@MiguelBarro,

I generated the static libraries, but I still can't build the project because foonathan_memory is missing. There is a foonathan_memory_vendor directory in the install folder, but there are no libraries inside. How can I generate other static libraries such as foonathan_memory-0.6.2.lib, libcrypto64MD.lib, libssl64MD.lib (Which were present when building from binaries) ?

In the cmake arguments there is a thirdparty options which is used to generate THIRDPARTY_fastcdr, THIRDPARTY_Asio,
THIRDPARTY_TinyXML2, and THIRDPARTY_android-ifaddrs. But I can't find the aforementioned libraries.

**Comment by MiguelBarro** [comment]
@HLATAFAT,

For the sake clarity I will split my answer:

## OpenSSL dependency

Fast-DDS docs explaining the installation procedure is [here](https://fast-dds.docs.eprosima.com/en/v2.1.0/installation/sources/sources_windows.html#openssl-sw).
The OpenSSL installers were, at the time of this answer, available at:

- https://slproweb.com/download/Win64OpenSSL-1_1_1h.exe 
- https://slproweb.com/download/Win32OpenSSL-1_1_1h.exe 

Once installed and to simplify CMake FindOpenSSL module working is adviceable to define the following environment variables (those are the default paths):

```bat
OPENSSL64_ROOT="C:\Program Files\OpenSSL-Win64"
OPENSSL32_ROOT="C:\Program Files (x86)\OpenSSL-Win32"
```
and update the PATH environmental variable to include both paths.

## eProsima/foonathan_memory_vendor

The only purpose of the eProsima/foonathan_memory_vendor is to make sure the [foonathan/memory](https://github.com/foonathan/memory) is available. If CMake can find foonathan/memory in the system the vendor package does nothing, if it doesn't then downloads and installs foonathan/memory within the workspace: `.\install\foonathan_memory_vendor\lib\foonathan_memory-0.6.2.lib`.

The only issue with this mechanism I am aware, takes place if a foonathan/memory 32bit installation is present in the system and Fast-DDS builds for 64bit (or viceversa). In this case the vendor package may be deceive and not install the foonathan/memory that matches the Fast-DDS build architecture. But this is a very odd case.

Please if the problem persist provide the steps you follow. The expected ones are available [here](https://fast-dds.docs.eprosima.com/en/v2.1.0/installation/sources/sources_windows.html#openssl-sw) and the only change expected is the colcon call to generate and use static libs in the examples and show progress:

```bat
colcon build --event-handlers console_direct+ --cmake-args -DBUILD_SHARED_LIBS=OFF -DCOMPILE_EXAMPLES=ON
```

**Comment by HLATAFAT** [comment]
@MiguelBarro 

Thank you very much for the comprehensive explanation, now linking to static libraries work. Could you please explain how can I link to dynamic libraries in the project, I tried the following without success:
win32:CONFIG(debug, debug|release): LIBS += "[install dir]\install\fastrtps\lib\fastrtps-2.1.lib"
win32:CONFIG(debug, debug|release): LIBS += "[install dir]\install\fastcdr\lib\fastcdr-1.0.lib"
DEPENDPATH += "[install dir]\install\fastcdr\bin"
DEPENDPATH += "[install dir]\install\fastrtps\bin"

**Comment by MiguelBarro** [comment]
@HLATAFAT,

colcon is a little cryptic sometimes and its cli mainly focus on CMake single-config generators like gcc or clang. In order to build using the debug config use (this works also for visual studio):

```bat
colcon build --event-handlers console_direct+ --cmake-args -DBUILD_SHARED_LIBS=OFF -DCOMPILE_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Debug
```

in order to generate dlls plainly use:

```bat
colcon build --event-handlers console_direct+ --cmake-args -DBUILD_SHARED_LIBS=ON -DCOMPILE_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Debug
```

note that remove the workspace build folder before rebuild is necessary to clear the CMakeCache (there is a colcon --cmake-clean-cache flag but sometimes it doesn't work).

**Comment by HLATAFAT** [comment]
@MiguelBarro 

Thanks a lot. Regarding the dynamic libraries, how can I link and use them in my project?

**Comment by MiguelBarro** [comment]
@HLATAFAT,

It depends solely on your build framework. For example:

## CMake projects

Fast-DDS provides CMake config files to simplify integration with other projects.  It's as simple as modifying your project CMakeLists.txt:

1. To search and introduce the *fastrtps* target 
```
find_package(fastrtps REQUIRED)
```
1. To add the *fastrtps* target as a dependency to your own targets
```
target_link_libraries(your_target_name fastrtps)
```

The Fast-DDS examples CMakeLists.txt show how to do it.  In order to locate the Fast-DDS package CMake may require some hints if not using colcon. The **CMAKE_PREFIX_PATH** variable must be set to the Fast-DDS installation path.

## Other build systems like Visual Studio

Fast-DDS must manually be introduced as a dependency:

1. Additional Include Directories: **installation path**\include
1. Preprocessor Definitions: **FASTRTPS_DYN_LINK**
1. Linker Additional Dependencies: **installation_path**\lib\fastrtpsd-2.1.lib 
   Note the library name lacks the *d* in the release version.

**Comment by HLATAFAT** [comment]
@MiguelBarro 

Thank you, I greatly appreciate your help.
