### ISSUE TITLE
Mingw build

### ISSUE THREAD

**Issue by serkanozen** [eProsima/Fast-DDS#1700]
Hi, 

Is it possible to build fastDds with mingw? Iwant to build it not with microsoft compiler but with mingw 4.9? Is it possible? 

Thanks
Serkan

**Comment by EduPonz** [comment]
Hi @serkanozen ,

We've been talking internally and we think it should be possible since there are CMake generators for Mingw. That being said, we've never tried it, nor we know about anyone doing it. Mind that Mingw is not an officially supported platform, so you might run into small issues along the process. In that case, maybe we can give you hand.

In any case, please do let us know how it goes. It'd be great if you could share your process.
