### ISSUE TITLE
Can not use interfaceWhiteList in XML file while using udpv6 to transport between two hosts

### ISSUE THREAD

**Issue by liyue75** [eProsima/Fast-DDS#1708]
I want to use ipv6 to transport and configure it in xml file. I disable builtin transport, use udpv6, specify metatrafficUnicastLocatorList, initialPeersList and defaultUnicastLocatorList.

## Current Behavior

If I don't use interfacewhitelist, they work well.
But when I specify interfaceWhiteList in xml file, they can send discovery message to the address in initiaPeersList but can not match each other.

## Steps to Reproduce

Pub's ipv6 address: fe80::889b:2f91:d82:6224
Sub's ipv6 address: fe80::78a9:5634:acf:cab4

1.Here is the xml file I use in publisher:
[pub.txt](https://github.com/eProsima/Fast-DDS/files/5877762/pub.txt)

2.Here is the xml file used in subscriber:
[sub.txt](https://github.com/eProsima/Fast-DDS/files/5877764/sub.txt)

## System information

- Fast-RTPS version: v2.1
- OS: Ubuntu18.04

## Aditional content
tcpdump capture 
![tcpdump](https://user-images.githubusercontent.com/53389739/105944952-421a0480-609f-11eb-8a6d-f29870a87e55.png)

**Comment by jparisu** [comment]
Hi @liyue75 ,
This is an already known bug in Fast-DDS in versions v2.1 and lower.
This bug arises from a very simple code typo.

This bug has been resolved in the already merged Pull Request  #1594 in master, where IPv6 was redesigned and tested properly.
Specifically, this error is solved in commit: https://github.com/eProsima/Fast-DDS/pull/1594/commits/63d97cebaea4dc0b6a9ec4c3fa6879bab158d1d0

We have planned to release the new Fast-DDS version v2.2 this very week, which is API compatible with v2.1.
In order to fix this problem, please, wait till new version is released. Or, in case you are using Fast-DDS from sources, feel free to apply the solution or cherry-pick the solution commit.

**Comment by liyue75** [comment]
@jparisu 
Thank you.
