### ISSUE TITLE
Question about memory [10728]

### ISSUE THREAD

**Issue by advancenOO** [eProsima/Fast-DDS#1774]
I am using fastdds v2.0.1 on device with low memory.
By running memoryTest, I find SendBuffersManager::init costs ~800k memory which contains 6 buffer(user, event, async-writer and 3 reception threads), and I am wondering if there is a way to reduce it.
And it shows that TypeObjectFactory::add_type_object is called for many times, is it optional?
In addition, I am not sure whether I should skip building socket on unnecessary interface as there are too many interfaces on my device.

Thanks for any light you shed.

**Comment by IkerLuengo** [comment]
You can limit the number of allocated sen buffers with [SendBuffersAllocationAttributes](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/eprosimaExtensions.html?highlight=SendBuffersAllocationAttributes#sendbuffersallocationattributes). For example, setting `dynamic = false` and `preallocated_number=1`. This has the effect of allocating a single buffer, so that any sending operation will have to wait until a free buffer is available.

You can configure this as the `allocation.send_buffers` attribute on both the new DDS API ([`DomainParticipantQos`](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/domain/domainParticipant/domainParticipant.html#domainparticipantqos)) and the legacy FastRTPS API ([`RTPSParticipantAttributes`](https://fast-dds.docs.eprosima.com/en/latest/fastdds/api_reference/rtps/attributes/RTPSParticipantAttributes.html#rtpsparticipantattributes)).

Regarding the interfaces on your device, you can [whitelist the interfaces](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/whitelist.html?highlight=whitelist#interface-whitelist), so that only those are used by your application.

Hope this info helps.

**Comment by advancenOO** [comment]
It works, thanks a lot!
