### ISSUE TITLE
[10730] For data-sharing delivery, subscriber loses messages while multiple publishers/subscribers are launched and one subscriber is terminated.

### ISSUE THREAD

**Issue by Barry-Xu-2018** [eProsima/Fast-DDS#1782]
Test case:
(Use one topic)

1. Start a publisher1 in terminal A
2. Start a subscriber1 in terminal B
3. Start a publisher2 in terminal C
4. Start a subscriber2 in terminal D
5. In terminal D, terminate subscriber2
6. Check received message in subscriber1

Qos Configuration: BEST_EFFORT_RELIABILITY_QOS, depth=10

## Expected Behavior
Subscriber1 continuously receives messages from publisher1 and publisher2 while subscriber2 is terminated.

## Current Behavior
Subscriber1 stops receiving messages. And wait a while (more than  8 seconds for my environment), subscriber1 continue to receive messages. But some messages are lost.

e.g.
...
Message HelloWorld 118 RECEIVED
Message HelloWorld 258 RECEIVED
Message HelloWorld 119 RECEIVED
Message HelloWorld 259 RECEIVED
Message HelloWorld 120 RECEIVED
Message HelloWorld 260 RECEIVED <== from publisher1
Message HelloWorld 121 RECEIVED <== from publisher2
Message HelloWorld 351 RECEIVED <== You will find the index is discontinuous. The index should be 261 instead of 351
Message HelloWorld 212 RECEIVED <== You will find the index is discontinuous. The index should be 122 instead of 212
Message HelloWorld 352 RECEIVED
Message HelloWorld 213 RECEIVED
Message HelloWorld 353 RECEIVED
Message HelloWorld 214 RECEIVED
...

## Steps to Reproduce
1. Start a publisher1 in terminal A
2. Start a subscriber1 in terminal B
3. Start a publisher2 in terminal C
4. Start a subscriber2 in terminal D
5. In terminal D, terminate subscriber2
6. Check received message in subscriber1

You can use this test program which is modified based on the example `HelloWorldExampleDataSharing`. https://github.com/Barry-Xu-2018/Fast-DDS/commits/topic-shared-memory-test. 

1. Execute ./DDSHelloWorldExampleDataSharing -t publisher -c 10000 in terminal A
2. Execute ./DDSHelloWorldExampleDataSharing -t subscriber in terminal B
3. Wait a while, execute ./DDSHelloWorldExampleDataSharing -t publisher -c 10000 in terminal C
4. Execute ./DDSHelloWorldExampleDataSharing -t subscriber in terminal D
5. In terminal D, do ctl+c
6. Check output in terminal B.

## System information

- Fast-RTPS version:  v2.2.0
- OS: ubuntu 20.04

**Comment by IkerLuengo** [comment]
This is an unexpected side effect of the sync mechanism we set between the publisher and the subscriber when using data-sharing. Specifically, a publisher is not allowed to reuse a cache change from the pool until all known subscribers have acknowledged they have processed it. Even on BEST_EFFORT or KEEP_LAST configurations.

I believe we should first describe the rationale behind this mechanism.

Publishers are generally faster than subscribers, in the sense that they can publish new data faster than the subscribers can process it. This is usually not a problem using regular transports, as the history configuration of publisher and subscriber deal with the data rate difference. But with data-sharing, the payloads are shared between publisher and subscriber, and since the pool of available cache changes is finite, things get a little tricky. The publisher consumes a cache change from the pool with every write and the subscriber frees it once processed. If the publisher goes at full throttle, eventually all the cache changes available at the pool will be consumed, and the subscriber will have a large queue of notifications to process.

Suppose the publisher is configured as KEEP_LAST or BEST_EFFORT. You may expect the oldest payload from the pool to be reused in the publisher for a new change. The subscriber has a mechanism to detect when a change that was notified has been reused before it was able to process it. Basically, while processing the old notification, it detects the inconsistency on the change and discards it (there will be a new notification in the queue for the new change that will be processed in turn). The problem is that, at full throttle, the publisher is faster writing the data than the publisher detecting the override and discarding the old one. At the end we have the subscriber going through its notification queue discarding all the changes, never catching up with the publisher. Thus, it never really reads anything.

This is why we decided to add a sync mechanism to make the publisher wait until all subscribers have had the opportunity to process a change before it can be recycled. Note that this mechanism independent from the DDS ACK, and refers to the management of the pool of changes, and not the history itself (publisher may have an empty history and still not be able to get a new buffer from the pool to write a new change).

In your tests, Subscriber2 is *killed*, so the publisher is not aware of its disappearance until the liveliness mechanism kicks in. Therefore, all messages are tagged as 'pending to be processed by subscriber2' and cannot be used. Eventually, the pool is emptied, and the publisher can no longer write new changes. Once the death of the subscriber is discovered, those changes are freed and the writing continues as usual.

On our example, the publisher is not checking the result of the write operation [here](https://github.com/eProsima/Fast-DDS/blob/85c1c50706e1bf81307cf023dfdf267cc1ae9a63/examples/C%2B%2B/DDS/HelloWorldExampleDataSharing/HelloWorldPublisher.cpp#L185) as it should. With the empty pool, this operation fails. However, the console output makes it look like it is working properly. I can see there is the same mistake on your tests.

So to some extent we can say that our data sharing implementation is always RELIABLE in the sense that the subscriber always has the opportunity to process the data. You found a side effect we didn't consider. The alternative is to remove this sync mechanism and enforce the application to limit the publication rate for BEST_EFFORT or KEEP_LAST configurations or they may not receive anything, but at least killing a subscriber will not stop the publishing.

We may need to further discuss if our current approach is the best one, given the failure you found. We'd like to know if you have any thoughts regarding this.

**Comment by Barry-Xu-2018** [comment]
@IkerLuengo  

Thank you so much for your detailed explanation.   
I will consider this and share my thoughts.

**Comment by Barry-Xu-2018** [comment]
@IkerLuengo 

Sync mechanism is necessary.  
For improving user experience，it is better to quickly find  the death of the subscriber.
Is it possible ?
(e.g. For writer side, while pool is empty, check the tag of oldest message to find which subscribe doesn't deal with this message. And check if the subscriber is living.)

**Comment by IkerLuengo** [comment]
You can easily make the writer be aware of the reader's death faster configuring the `lease_duration` in the [LivelinessQosPolicy](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/standardQosPolicies.html?highlight=lease_duration#livelinessqospolicy) of the DataWriterQos. It basically defines how much time the writer will wait until it considers an unresponsive reader as dead.

**Comment by Barry-SH** [comment]
> You can easily make the writer be aware of the reader's death faster configuring the lease_duration in the LivelinessQosPolicy of the DataWriterQos. It basically defines how much time the writer will wait until it considers an unresponsive reader as dead.

Thank you. I will try it.

**Comment by Barry-Xu-2018** [comment]
> You can easily make the writer be aware of the reader's death faster configuring the lease_duration in the LivelinessQosPolicy of the DataWriterQos. It basically defines how much time the writer will wait until it considers an unresponsive reader as dead.

Thank you. I will try it.

**Comment by Barry-Xu-2018** [comment]
@IkerLuengo 

I have confirmed that configuring the `lease_duration` is effective.  

```c++
DomainParticipantQos pqos;
...
pqos.wire_protocol().builtin.discovery_config.leaseDuration = {0, 10000000};
pqos.wire_protocol().builtin.discovery_config.leaseDuration_announcementperiod = {0, 5000000};
```

**Comment by fujitatomoya** [comment]
@IkerLuengo @MiguelCompany 

appreciate for the quick response and sharing the thoughts :+1: 

sorry, i was late to catch up with this.

i left some comments here, i might be missing something...

> Publishers are generally faster than subscribers, in the sense that they can publish new data faster than the subscribers can process it.

i am not sure if it is general or not. but technically this can be easily possible.

> At the end we have the subscriber going through its notification queue discarding all the changes, never catching up with the publisher. Thus, it never really reads anything.

this seems to be a `best effort` for me with data sharing. but at least user should be able to detect this situation and tune the shared memory configuration to make it bigger.

> mechanism to make the publisher wait until all subscribers have had the opportunity to process a change before it can be recycled.

it does not seem the publisher waits on writing, but dropping messages. when the pool is full, writer disposes the message w/o notification?

> always RELIABLE in the sense that the subscriber always has the opportunity to process the data.

i am not convinced on this very much. as fa as i see, this is the behavior for RELIABLE, and it does not tell me to drop BEST_EFFORT. and as you provided the option for lease_duration, user application still can have the control. but at least user must be able to know that write is failing because of shared memory pool is empty.

> The alternative is to remove this sync mechanism and enforce the application to limit the publication rate for BEST_EFFORT or KEEP_LAST configurations or they may not receive anything, but at least killing a subscriber will not stop the publishing.

i'd say we can keep sync mechanism for RELIABLE, but not used for BEST_EFFORT or KEEP_LAST configurations. again user must be able to know that overwritten is happening and message is overwritten on writer and receiver side. i think this is application responsibility to tune the shared memory buffer and publisher/subscription rate to access data. (for me, this seems that there is hardware resource limitation, and what do you want?)

thanks :smiley:

**Comment by IkerLuengo** [comment]
> it does not seem the publisher waits on writing, but dropping messages. when the pool is full, writer disposes the message w/o notification?

The default timeout to wait for a buffer to write a new change is 100 ms (), if you didn't change that, the waiting will be rather short, and will fail quickly. However, the DataWriter does inform about the error when this happens, returning a `ReturnCode_t::RETCODE_OUT_OF_RESOURCES` on the `write` operation. It is our test class `HelloWorldPublisher` the one that is not checking the outcome of this operation and jumps to the next message [here](https://github.com/Barry-Xu-2018/Fast-DDS/blob/fe71238c2e45c6dcbefcd8a955a9c726768c7a97/examples/C%2B%2B/DDS/HelloWorldExampleDataSharing/HelloWorldPublisher.cpp#L248)

> i'd say we can keep sync mechanism for RELIABLE, but not used for BEST_EFFORT or KEEP_LAST configurations.

I think you have a point there. We are making some changes in #1817 including the removal of the ACK mechanism on BEST_EFFORT and KEEP_LAST, so that we are faithful to the user's expectations. Overridden changes are detected and removed on the reader side before giving them to the user. In the same PR we are also removing the interprocess locks and redesigning the sync mechanism to avoid the need to lock, as we found interprocess locks are very slow.

Cheers

**Comment by fujitatomoya** [comment]
> returning a ReturnCode_t::RETCODE_OUT_OF_RESOURCES on the write operation.

makes sense.

**Comment by fujitatomoya** [comment]
@Barry-Xu-2018 

as we discussed today, it would be nice to check this issue with https://github.com/eProsima/Fast-DDS/pull/1817.

**Comment by Barry-Xu-2018** [comment]
After applying #1817, I confirm this issue is fixed.   
So I close this issue.
