### ISSUE TITLE
Сompilation error with Visual Studio 2015 [13603]

### ISSUE THREAD

**Issue by i-and** [eProsima/Fast-DDS#1908]
There is an error compiling the following lines of the `src/cpp/utils/collections/FixedSizeQueue.hpp` file with Visual Studio 2015:
~~~ c++
 class iterator
    {
    public:

        using iterator_category = std::bidirectional_iterator_tag;
        using value_type = FixedSizeQueue::value_type;
        using difference_type = FixedSizeQueue::difference_type;
        using pointer = FixedSizeQueue::pointer;
        using reference = FixedSizeQueue::reference;
~~~
~~~
FixedSizeQueue.hpp(63): error C2061: syntax error: identifier 'value_type'.....
~~~
Fixes with the help of related modifications:

~~~ c++
        using value_type = _Ty;
        using difference_type = std::ptrdiff_t;
        using pointer = _Ty*;
        using reference = _Ty&;
~~~

**Comment by MiguelCompany** [comment]
VS 2015 is not a Tier 1 platform, and thus it is neither tested nor supported

> Fixes with the help of related modifications:

If you know how to fix this, a PR is more than welcome.

**Comment by JLBuenoLopez-eProsima** [comment]
I am going to proceed and close this issue because it refers to a non-supported platform/architecture (see our officially supported platforms [here](https://github.com/eProsima/Fast-DDS/blob/master/PLATFORM_SUPPORT.md)). Also, the user already provided a workaround to solve the issue in case there is someone using also Visual Studio 2015.
