### ISSUE TITLE
Program with Fast-DDS library (v2.3.0) freezes when exiting it [13607]

### ISSUE THREAD

**Issue by i-and** [eProsima/Fast-DDS#1921]
On Windows 7, there was a program freeze in the process of exiting the `main()` function. 

After debugging, it turned out that the reason lies in the fact that the destructor of the static `watch_dog_instance` object of the `SharedMemWatchdog` class is trying to signal and wait for the completion of the `SharedMemWatchdog::run()` thread, which has already been actually destroyed by the UCRT library. 
~~~ c++
  ~SharedMemWatchdog()
  {
      exit_thread_ = true;
      wake_up();
      thread_run_.join();
  }
~~~
In fact, at the time of calling the `~SharedMemWatchdog()` destructor, only one "Main thread" is present in the application and the `wake_run_cv_.notify_one()` call from `wake_up()` hangs.

I propose to introduce a static method `delete_instance()` in the interface of the `DomainParticipantFactory` class, which would explicitly stop threads and then destroy global/static objects in the correct sequence: first the tasks registered in `SharedMemWatchdog`, and then the object of the `SharedMemWatchdog` class itself. 
In this case, the `DomainParticipantFactory::delete_instance()` method must be called by the client code before exiting `main()`.

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @i-and,

Sorry for the late reply. Some refactors have been done in the last months in order to ensure the correct order destruction of the singletons created by Fast DDS. However, these fixes were not applied to Fast DDS v2.3.x as this branch is no longer alive (see [Fast DDS release support](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md) for more information). Could you check if this still happening in master? If so, please feel free to open a new issue. For the moment I am going to close this one as this is not going to be solved in Fast DDS 2.3.x.
