### ISSUE TITLE
UDPv6 needs default IPv6 address [11564]

### ISSUE THREAD

**Issue by RFRIEDM-Trimble** [eProsima/Fast-DDS#1928]
The [DDS 2.3](https://www.omg.org/spec/DDSI-RTPS/2.3/Beta1/PDF) standard only dictates what the IPv4 UDP default address is in section 9.6.1.4. FastDDS does not currently implement a standard IPv6 address.

Thus, I don't think there is a right way to initialize a default IPv6 address multicast locators, but there should be two requirements. 
1. It is an IPv6 address
2. It is a multicast address

Currently, one address is used [here](https://github.com/eProsima/Fast-DDS/blob/55a28911b385b1802de11845c8321abdee01bdce/src/cpp/rtps/transport/UDPv6Transport.cpp#L144) and another [here](https://github.com/eProsima/Fast-DDS/blob/55a28911b385b1802de11845c8321abdee01bdce/src/cpp/rtps/transport/UDPv6Transport.cpp#L206), the latter not being a valid IPv6 address. This ticket is to address that problem.

For IPv4, the standard is correctly followed in the code [here](https://github.com/eProsima/Fast-DDS/blob/master/src/cpp/rtps/transport/UDPv4Transport.cpp#L193)

A proposal would be this. 

1. Change the above IPv6 defaults to be a valid IPv6 multicast address
2. Use an IPv4 to IPv6 mapped address of `FF1E::FFFF:239.255.0.1` to follow [RFC4291](https://tools.ietf.org/html/rfc4291#section-2.7) for the default IPv6 address for Fast-DDS
    * FF at the beginning is multicast
    * `flgs` T is set to 1 to `transient multicast address`
    * `flgs` `P` is also set to 1 to indicate multicast address assigned based on the network prefix following [RFC3306](https://tools.ietf.org/html/rfc3306)
    * `scop` is set to Global Scope `E`
    * `flgs` `R` is set to 0
    * Note: The above mapped address representation isn't supported within the Fast-DDS locator constructor, so it will need to be reformatted.
3. Take the hard-coded addresses for both IPv4 and IPv6 and put them in a header file for users to access if needed

While you're at it, might as well put that address in a header file so other applications can use it. 

I'm happy to do the PR; just want feedback on the above. 

_Originally posted by @RFRIEDM_Trimble in https://github.com/eProsima/Fast-DDS/issues/1640#issuecomment-776184596_

**Comment by EduPonz** [comment]
Hi @RFRIEDM-Trimble ,

Thanks for your detailed report! We have take a look at it and everything seems alright with it. Just a couple of things:

* Using IPv4-v6 mapping makes a lot of sense. However, as you say, `FF1E::FFFF:239.255.0.1` is not a format we currently support for constructing or parsing. I'd suggest using something like the [Locator constructor](https://github.com/eProsima/Fast-DDS/blob/master/include/fastdds/rtps/common/Locator.h#L109), and then set the address with one of the [`IPLocator::setIPv6`](https://github.com/eProsima/Fast-DDS/blob/master/include/fastdds/rtps/common/Locator.h#L109) functions. Mind that the `239.255.0.1` part would need to be translated into hex double words
* Since the default IPv4 multicast address is not included in any header file, we don't see the need for the IPv6 one to be either. From our point of view, these addresses are internal to the RTPS protocol and users should not need to know about them at all.

A PR on your part would indeed be most welcome!

Again, thanks for the interest and the thorough report.

**Comment by RFRIEDM-Trimble** [comment]
No problem. 

Yep; I'll adjust the format to be compatible the API's and submit a PR soon.

**Comment by RFRIEDM-Trimble** [comment]
I created it with `FF1E::FFFF:239.255.0.1` which expands to `ff1e:0000:0000:0000:0000:ffff:efff:0001` and compresses back down to `FF1E::ffff:efff:1`

**Comment by JLBuenoLopez-eProsima** [comment]
I will proceed and close this issue as the related PR #1959 was merged several months ago (May 2021) and it was also backported to previous branches (from `2.0.x` onward)
