### ISSUE TITLE
Question: How can publisher get a subscirber unmatch notification immediately ?

### ISSUE THREAD

**Issue by normalscene** [eProsima/Fast-DDS#1934]
When a matched subscriber is killed or removed, it takes around 5 seconds or more for the publisher
to get notified that the subscriber is not available. Is there any way to speed it up to make it immediate 
or instantaneous (if possible). 

## Expected Behavior

If a subscriber is no more available - I expect the publisher to get a 'unmatch' immediately.

## Current Behavior

Currently it takes around 5 seconds or more for the publisher to get an unmatch

## Steps to Reproduce

Run a default pub/sub app with default settings and this behavior can be observed

## System information

- Fast-RTPS version: libfastrtps.so.2.0.0
- OS:  Ubuntu 16/18/20
- Network interfaces: 
                      
- ROS2: 
        

## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by EduPonz** [comment]
Hi @normalscene ,

From your description, it seems that the subscriber application is being killed rather than having an clean exit. If that is the case, the publisher participant simply thinks that the subscriber is still alive until the subscriber's lease expires.

Participants advertise their lease duration alongside their discovery information, and they periodically send a hailing message to let the peers know that they are still alive (you can read more about it [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/general_disc_settings.html#general-discovery-settings)). When a participant leaves the network, it sends a final message to let the others know that it's leaving. My suspicion is that your subscriber application is being killed, so this last final message is not being sent. Then, once the lease duration has expired without the publisher receiving any message from the susbcriber, the publisher "decides" the subscriber is dead. With the default lease duration settings, this can, in the worst case, take up to 20 seconds, however you can configure those parameters yourself either by code, or by [XML](https://fast-dds.docs.eprosima.com/en/latest/fastdds/xml_configuration/domainparticipant.html#discovery-config).

How are you shutting down your subscriber? Are you sending a SIGKILL, or are you removing it in code?

Thanks!

**Comment by normalscene** [comment]
Hello @EduPonz 

Yes - the subscriber is being killed rather than having a clean exit - that is absolutely correct.
I was killing the application using CTRL+C, for now but soon I shall setup a signal handler
to do the job.

I will attempt to put the settings into effect as pointed by you. Thanks for pointing it out to me.

Speaking of _clean exit_ - how should we shut down a pub/sub if we need to ?

is the reader/writer -> close() method the way to go?

Currently

**Comment by EduPonz** [comment]
Hi @normalscene ,

I think you can use the [DDS HelloWorld example](https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B/DDS/HelloWorldExample) as a guide for a clean exit.

If instead of the DDS API, you're using the deprecated Fast RTPS one, the example is [here](https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B/HelloWorldExample).

**Comment by MiguelCompany** [comment]
It seems the questions on this issue have been answered. Could you close this issue, @normalscene?

**Comment by normalscene** [comment]
Thanks @EduPonz  for your support earlier. My query was resolved successfully - closing the issue now.
