### ISSUE TITLE
Publisher write call blocks forever [13644]

### ISSUE THREAD

**Issue by ji-sep** [eProsima/Fast-DDS#2002]
I’m working in a project with a lot of publishers and subscribers (around 500 publishers and 400 subscribers).

Sometimes, the publisher write call is blocked forever.

The issue is similar to: #1042 ... that is supposed is already fixed in 2.3.0 version

## System information

- Fast-RTPS version: 2.3.0
- OS: Ubuntu 18.04
- Network interfaces: eth0 and lo

**Comment by JLBuenoLopez-eProsima** [comment]
Hi, @ji-sep,

Sorry for the late reply! In order to help you we would need some more information about how to reproduce your issue with a minimal example. Issue #1042 provided a way to reproduce it and that allowed us to fix it. The write call may block under certain circumstances depending also on the QoS being used (see more information in [this article](https://www.eprosima.com/index.php/resources-all/performance/dds-asynchronous-vs-synchronous-publishing)). So all the information you can share with us may help solving your issue.

**Comment by JLBuenoLopez-eProsima** [comment]
I am going to close this issue due to inactivity. More information is required and no answer has been received in the last month (see [CONTRIBUTING](https://github.com/eProsima/Fast-DDS/blob/master/CONTRIBUTING.md#issues)). Feel free to reopen providing the required information, though opening a new ticket using the issue template is advisable.
