### ISSUE TITLE
Preallocated memory writers fails

### ISSUE THREAD

**Issue by Benatti1991** [eProsima/Fast-DDS#2082]
The same program, when DataWriterQos history_memory_policy is set to PREALLOCATED_WITH_REALLOC_MEMORY_MODE works fine (although the reallocation is not efficient). When I set it to PREALLOCATED_MEMORY_MODE it fails, even though the message passed to the writer is rather small (250 bytes). I am probably missing some buffer size setting, but I couldn't figure out, from the documentation, anything else than transport buffer size, and that seems to have no effect on this issue.
Thanks,
Simon

## System information
Both Windows and Linux machines 

- Fast-RTPS version: 2.3.3

**Comment by EduPonz** [comment]
Hi @Benatti1991 ,

This is normally caused by unbounded data types (such as those containing sequences or strings for example). When using `PREALLOCATED_MEMORY_MODE`, the memory for the samples in the history is allocated on starting up, having a maximum for the elements in unbounded types (e.g. for sequences, 100 elemets are allocated if I recall correctly). If a message arrives that exceeds those limits, then it does not fit into the allocated memory. That's why using `PREALLOCATED_WITH_REALLOC_MEMORY_MODE` solves the problem, cause with that policy, if the message does not fit in the allocated space, then some more memory will be allocated for it elsewhere.
Maybe taking a look at your message definition (IDL file) will help clarifying the issue so we can give you more precise advice.

**Comment by Benatti1991** [comment]
The IDL file is rather simple, since the byte buffer is then passed to a FlatBuffer based function (we rely on FlataBuffer) to decode the message:
```
struct SynDDSMessage {
  unsigned long rank;
  sequence<octet> data;
};
```
The reason for this is that DDS is only one of the possible communication strategies we adopt, and all these rely on FlatBuffer.

Simon

**Comment by MiguelCompany** [comment]
@Benatti1991 If you know the maximum possible size for `data`, you could use a bounded sequence.

```
struct SynDDSMessage {
  unsigned long rank;
  sequence<octet, 1024> data;
};
```

**Comment by EduPonz** [comment]
To complement on @MiguelCompany answer, as describer in https://github.com/eProsima/Fast-DDS/issues/1205#issuecomment-626489994, when defining an unbounded sequence in your IDL while using `PREALLOCATED_MEMORY_MODE`, the implementation will allocate 100 elements for the sequence. This means that you'll get errors if you try to send sequences with more than 100 elements on them.

**Comment by Benatti1991** [comment]
Changing the idl file effectively changes the memory allocation. 
(It didn't solve my performance issue but that's a different story for a different day.)
Thanks,
Simone
