### ISSUE TITLE
Expected behavior when interfaces change during runtime

### ISSUE THREAD

**Issue by maxikrie** [eProsima/Fast-DDS#2097]
Hello,

I am wondering what the expected behavior is when interfaces change during runtime. Specifically, I am running the ShapesDemo as a publisher on one machine connected to a router through Ethernet. I have a second machine running the ShapesDemo as subscriber, which is connected through Ethernet as well. This works as expected.

When I now disconnect Ethernet on the second machine and connect it through WiFi, it does no longer receive data from the publisher. Only after I close the ShapesDemo, reopen it and subscribe to the topic as before, it again receives data as expected (leaving the ShapesDemo open and simply removing and resubscribing to the topic is not sufficient).

I would expect Fast-DDS to find a new route through a different interface during runtime just like, e.g. the ping command does - is this not the case or is this a particular problem of the ShapesDemo?

As always, many thanks!
Max

**Comment by EduPonz** [comment]
Hi @maxikrie ,

What you describe is the expected behaviour. As of today, Fast DDS scans the network interfaces only once on starting up. This means that if the available interfaces change over time, Fast DDS will not detect it (that's way if you re-start then it works again). You may be interested in contacting support@eprosima.com for a discussion on a possible feature request.

**Comment by maxikrie** [comment]
Thanks for quick response! I didn't think it was related to https://github.com/eProsima/Fast-DDS/issues/1880, but I guess it is exactly that.

I can confirm that if the second machine was already connected to the router through Ethernet AND WiFi when ShapesDemo was started, I can gracefully turn on/off either interfaces and continuously receive data. When I turn both off and either one back on, it does pick up data again.

One follow-up question: which interface is picked initially when multiple interfaces are available?

Thanks!

**Comment by EduPonz** [comment]
Hi @maxikrie 

> One follow-up question: which interface is picked initially when multiple interfaces are available?

All of them. Fast DDS will use all the available interfaces unless otherwise specified (see [interface whitelisting](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/whitelist.html)). This in fact means that the same message would be send over enthernet and WiFi in your case.

**Comment by JLBuenoLopez-eProsima** [comment]
I am going to close this issue as it has already been answered.
