### ISSUE TITLE
Question about share memory

### ISSUE THREAD

**Issue by advancenXX** [eProsima/Fast-DDS#2114]
I find that I could use share memory transport by setting useBuiltinTransports to false and adding SharedMemTransportDescriptor in my every single application.
I am wondering if I could set shm as the default transport, so that it will work for all my applications. I have enabled -DSHM_TRANSPORT_BUILTIN but it did not work.

By the way, using useBuiltinTransports will loss package when transmit ~1MB data within device, and that is why I turn to shm.

**Comment by MiguelCompany** [comment]
Shared memory transport is included on the builtin transports since [v2.0.2](https://github.com/eProsima/Fast-DDS/releases/tag/v2.0.2), so if you are using a version greater than 2.0.2, shared memory transport will be used by default for communications within the same host.

> By the way, using useBuiltinTransports will loss package when transmit ~1MB data within device, and that is why I turn to shm.

You could try setting `send_socket_buffer_size` on the participant's [TransportConfigQos](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/eprosimaExtensions.html#transportconfigqos)

**Comment by advancenXX** [comment]
Thanks!
