### ISSUE TITLE
How to keep transmission if client's IP address change when using Discovery Server?

### ISSUE THREAD

**Issue by liyue75** [eProsima/Fast-DDS#2146]
I have a portable device which sends data to my desktop. The device use a 4G module to access the network. Here is the structure of my program.
![example](https://user-images.githubusercontent.com/53389739/129315029-cf984559-e513-4c20-aa33-5ea523a15dd2.png)

The 4g module can obtain a temporary global unicast IPv6 address each time it starts up, and my desktop gets a temporary global unicast IPv6 address. In order to let them discovery each other, I run a DDS Server on cloud which has a fixed IPv6 address, the pub and sub would send their meta data to the DDS Server first,  then start user data transmision.

## Expected Behavior
The portable device use a 4G module to access network, the 4G module sometimes loses network connection, and will auto restart. After it restarts, it will obtain a new and different global IPv6 address.
When the program is running, I expect the subscriber can still receive data from publisher after the publisher get a new IPv6 address.

## Current Behavior
1. When the publisher starts running, the subscriber can receive data.
2. When the 4G module lose connection, the publisher is still running,  the subscriber can not receive data.
3. The 4G module will auto restart and get a new IPv6 address, after that, the publisher is still running, but the subscriber still can  not receive data.

I think this seems to have something to da with DDS Discovery strategy. When using Discovery Server, Clients seems only send their PDP data to Server once when they are creating. After Clients have been created, no more PDP data will be sent, they will only send EDP data periodically. So I guess the reason of the problem: If the pub's IP changes, the sub does not know, because the pub will not send PDP data to the Server. 

In order to let the subscriber receive data again, my solution now is to manually stop the publisher, and restart the publisher. But this is inconvenient because I do not konw when th IP will change.
Is there any way to automatically detect IP changes in the program and then tell the Discovery Server or restart the program?
Or how to let Clients send their PDP data to Discovery Server periodically?

## System information

- Fast-RTPS version:  v2.3.0
- OS:  Ubuntu18.04

**Comment by EduPonz** [comment]
Hi @liyue75 ,

This is indeed a cool setup you've got!

Unfortunately, what you are experiencing is the current expected behaviour. During the creation of the `DomainParticipant`, the network interfaces are scanned to get the available IPs. However, this only happens here, so Fast DDS cannot currently handle a change in the address of one of the interfaces. Also, your current solution is the only possible one as of right now.

Regarding how to detect such changes in your application, from a quick search I found ways of doing this:
* https://stackoverflow.com/questions/50943190/detect-network-interface-change
* https://stackoverflow.com/questions/579783/how-to-detect-ip-address-change-programmatically-in-linux/2353441

Nonetheless, what you describe sounds like a cool feature to include in Fast DDS, so I may suggest contacting evaluation.support@eprosima.com about it!

**Comment by EduPonz** [comment]
I'm labeled the issue as `question` and `enhancement`. I'll close it for now. Please feel free to re-open at any time.

**Comment by waldt** [comment]
@EduPonz Please consider re-opening the issue. Working over rapidly churning networks with intermittent connectivity is increasingly important use-case for many. (For reasonably detailed use scenario description, see https://www.rti.com/blog/going-mobile-with-connext-dds-5.3)
