### ISSUE TITLE
Feature request: Support a DNS name in ROS_DISCOVERY_SERVER

### ISSUE THREAD

**Issue by anguslees** [eProsima/Fast-DDS#2153]
I am running ROS2 (galactic) nodes on Kubernetes, which means broadcast/multicast discovery doesn't work so well.  The fastdds discovery server, however works great!

Right now, `ROS_DISCOVERY_SERVER` env var only supports a literal IPv4 address.  For my (Kubernetes) case, I _can_ hardcode an IPv4 literal in the config, but it would be nicer if I could use a DNS name here instead.  I imagine this would be useful in some other environments too.

**Comment by EduPonz** [comment]
Hi @anguslees ,

I've got good news for you! We merged #2140 in master yesterday, which brings exactly the functionality you're looking for. You can read some documentation about it [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/discovery_server.html#configure-discovery-server-locators-using-names), [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/env_vars/env_vars.html#ros-discovery-server), and [here](https://fast-dds.docs.eprosima.com/en/latest/fastddscli/cli/cli.html#discovery).

Mind that the current Fast DDS branch for ROS 2 Galactic is [2.3.x](https://github.com/ros2/ros2/blob/galactic/ros2.repos#L34-L37) if you're building from sources, or [v2.3.1](https://github.com/ros2/ros2/blob/galactic-release/ros2.repos#L34-L37) if you are installing via binaries (next Galactic sync will include v2.3.4). Nonetheless, if you are building ROS 2 Galactic [from sources](https://docs.ros.org/en/galactic/Installation/Ubuntu-Development-Setup.html), you can just checkout to Fast DDS' master branch and re-build; since v2.3.1, v2.3.4, master are API compatible at the moment.

Please do give it a try and tell us how it goes, we are excited to hear about it! I'll close the issue for now, but please feel free to re-open at any time.
