### ISSUE TITLE
Ros2cli topic , echo , hz not working in root directory [13686]

### ISSUE THREAD

**Issue by Narendarselva** [eProsima/Fast-DDS#2162]
## Expected Behavior
cd ~
Ros2 topic list should show the list of topics.

## Current Behavior
cd ~
Ros2 topic list is not showing any topics.

But able to see the topics when i ran the ros2 topic list on some other directory.
This is weird but out of clues.
Kindly share some in-sites.

## Steps to Reproduce
1. Start a node in root directory
2. open new terminal and try running ros2 topic list .

## System information
ubuntu 16.04

- Fast-RTPS version: 2.1.1
- OS: Ubuntu 16.04
- ROS2: crystal

**Comment by JLBuenoLopez-eProsima** [comment]
Sorry @Narendarselva,

ROS 2 Crystal is no longer supported as it reached end of life in December 2019. What you are describing is really weird and we have not seen this behavior in more recent releases of ROS 2. I am going to close this issue due to not being officially supported. Feel free to reopen if you try it in a more recent and supported ROS 2 release and find the issue happening also there.
