### ISSUE TITLE
Participant ID and port [12548]

### ISSUE THREAD

**Issue by TuMePJlaH** [eProsima/Fast-DDS#2192]
Hello!
I am trying to understand how the RTPS Layer works and how the Participant ID and port for communication are issued.
I ran the example from Getting Started by adding a function to the DomainParticipant class (to access the RTPSParticipant):
```cpp
fastrtps::rtps::RTPSParticipant* DomainParticipant::rtps_participant() {
    return impl_->rtps_participant();
}
```
Then I look at the Participant ID in the RTPSParticipant class and it is always 1.
No matter how many publishers and subscribers I launch in different windows, the participant ID is always 1.

The ROS2 Foxy manual says: "For each ROS 2 process running on a computer, one DDS “participant” is created.",
and the formula is written, how the port number is calculated depending on the participant ID.

If I look at tcp dump, I see different participant IDs:
![image](https://user-images.githubusercontent.com/17141754/132242347-891a456a-7790-4576-86a0-35c72beb4726.png)

Can you explain how (and where in the code) is the port allocation and how is the participant ID calculation for RTPS?

**Comment by MiguelCompany** [comment]
Wireshark generates that information from the UDP destination port of the datagram exclusively. The participant ID on the RTPSParticipant is "the participant index of all the participants in the same process". That's why you are always seeing 1 as the participant ID.

The port allocation is done [here](https://github.com/eProsima/Fast-DDS/blob/4a27fbbbeb08ad83ffa10422eeaa201017382905/src/cpp/rtps/participant/RTPSParticipantImpl.cpp#L1473). As you can see, if the port cannot be open (i.e. `BuildReceiverResources` returns false), it means the port is already in use, and a new port (using participantIDGain) is tried.

**Comment by TuMePJlaH** [comment]
Thank you for  your response! Now I get it.
