### ISSUE TITLE
How do subscribers return received data？

### ISSUE THREAD

**Issue by XiaomuWang** [eProsima/Fast-DDS#2197]
I want my subscribers to be able to return the data they receive instead of just printing it out on the screen, should I do it on the function of onNewDataMessage？
The onNewDataMessage function code is as follows:
```c++
void HelloWorldSubscriber::SubListener::onNewDataMessage(
        Subscriber* sub)
{
    if (sub->takeNextData((void*)&hello, &info))
    {
        if (info.sampleKind == ALIVE)
        {
            this->n_samples++;
            // Print your structure data here.
            //logError(HW, "RECEIVED " <<  hello.index());
            std::cout << "[RTCP] Message " << hello.message() << " " << hello.index() << " RECEIVED" << std::endl;
        }
    }
}
```

**Comment by XiaomuWang** [comment]
The code I refer to is HelloWorldExampleTCP in the sample code: https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B/HelloWorldExampleTCP

**Comment by EduPonz** [comment]
Hi @XiaomuWang ,

`onNewDataMessage()` returns void, so you cannot "return" the data from the callback. What you could do in you application is for instance append the new sample into a collection that you can access from outside the callback's scope, and notify the application thread about the new data event using some flag or condition variable. Nonetheless, that's merely one approach to it, but there are many depending on what it is that you're trying to achieve.

On a side note, I recommend you take a look at the more [modern version of the example](https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B/DDS/HelloWorldExampleTCP), which uses the DDS API instead of the old and not maintained Fast RTPS API

**Comment by XiaomuWang** [comment]
Thank you very much! I've solved the problem!
