### ISSUE TITLE
between clients [12550]

### ISSUE THREAD

**Issue by zengdapang** [eProsima/Fast-DDS#2210]
Use fastdds and tcp under wan or internet to communicate between server and client, but the same domain and topic cannot be used for communication between clients, is this normal?

**Comment by jparisu** [comment]
Hi @zengdapang 

I am afraid I would need more information about the network architecture you are working with, and the configurations (.xml files or entities creation code) that you are using to configure your workspace, as the Fast DDS version you are using.
Check the Fast DDS documentation for information about configuring TCP in WAN https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/tcp/tcp.html#wan-or-internet-communication-over-tcpv4
I would also recommend you to check the Fast DDS example `HelloWorldExampleTCP` https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B/DDS/HelloWorldExampleTCP

Some tips that I can give you so far:
- Be careful with the terms in the documentation and examples. 
    - There are a Participant Type `SERVER` and `CLIENT` that refers to the Fast DDS Discovery Protocol `Discovery Server Discovery Protocol` https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/discovery_server.html#discovery-server
    - TCP protocol has its own server and client, and you should configure them differently in Fast DDS depending on your network architecture (there is no relation between Publishers or Subscribers and TPC servers or TCP clients) 

- In order to communicate in Wide Area Networks (WAN) with Network Address Translation (NAT) (i.e. communicating two endpoints that each one is behind a different router) you will have to:
    - Use the public IP (the IP of your router)
    - Allow Port Forwarding in your router configuration, and open the port of the TCP server from the router to the host where Fast DDS is running

**Comment by JLBuenoLopez-eProsima** [comment]
I am going to close this issue due to inactivity. More information was required and no answer has been received in the last few months (see [CONTRIBUTING](https://github.com/eProsima/Fast-DDS/blob/master/CONTRIBUTING.md#issues)). Feel free to reopen providing the required information, though opening a new ticket using the issue template is advisable.
