### ISSUE TITLE
Profile XML file not loaded when giving a full path [13705]

### ISSUE THREAD

**Issue by omertal88** [eProsima/Fast-DDS#2295]
Hello all,

I was trying to run a ros2 demo talker node using a profile which disables multicast (see: https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/disabling_multicast.html).

First I tried:
`RMW_IMPLEMENTATION=rmw_fastrtps_cpp FASTRTPS_DEFAULT_PROFILES_FILE=/home/omer/SOME_PATH/DEFAULT_FASTRTPS_PROFILES.xml ros2 run demo_nodes_cpp talker`
and I got these errors:
```
2021-10-26 13:07:04.841 [XMLPARSER Error] Error adding profile 'disable_multicast' from file 'DEFAULT_FASTRTPS_PROFILES.xml' -> Function extractParticipantProfile
2021-10-26 13:07:04.841 [XMLProfileManager Error] Could not extract any profile -> Function extractProfiles
```

Then I tried to use a relative path (the file was located on my current working directory) and it worked like a charm.

Is that an expected behavior or some kind of bug?

Thanks in advance.

Best wishes,
Omer

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @omertal88,

Sorry for the late reply! As far as I understand, the XML file is being loaded the two times. The issue is that the profile is issuing an error when being loaded in one of the cases. Are you sure the Fast DDS application is loading the same XML file in both cases? Could you provide the XML file you are using so we may try to reproduce your issue?

**Comment by JLBuenoLopez-eProsima** [comment]
I am going to close this issue due to inactivity. More information is required and no answer has been received in the last month (see [CONTRIBUTING](https://github.com/eProsima/Fast-DDS/blob/master/CONTRIBUTING.md#issues)). Feel free to reopen providing the required information, though opening a new ticket using the issue template is advisable.
