### ISSUE TITLE
Question about HelloWorld example

### ISSUE THREAD

**Issue by Nir-Az** [eProsima/Fast-DDS#2343]
Hi, I read the documentation and trying to understand the example of "HelloWorld"

I am not sure what is the difference between [this](https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B/HelloWorldExampleSharedMem) and [this](https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B/DDS/HelloWorldExampleSharedMem) examples.

what does the DDS subfolder means?

I am looking for examples that will help me understand how to use fast-dds shared memory (with zero copy as an extra)

Thanks

**Comment by EduPonz** [comment]
Hi @Nir-Az ,

Fast DDS exposes two different APIs to interact with the library:

* Fast RTPS API: Library's API prior to v2.0.0. It is no longer maintained, as it was deprecated in v2.0.0 in favor of the DDS API. The Fast RTPS API will be removed in v3.0.0
* DDS API: DDS specification compliant API. It is the recommended API, as it is the one maintained and the one featured in the documentation.

The DDS subfolder was added in v2.0.0 to ship the same examples but showcasing the DDS API. The previous examples were left where they are (instead of moved to a different sub-folder) to maintain any possible direct links to them. However, they will most likely be moved in the future into a Fast RTPS folder.

I'm closing the issue for now, but please feel free to re-open it if needed.

**Comment by Nir-Az** [comment]
Thanks @EduPonz , your explanation helped.

I got a couple more questions now that I started playing with the examples.

1. I see that on the DDS shared memory example not only shared memory transport layer is used, but also UDP ([here](https://github.com/eProsima/Fast-DDS/blob/fc4fade0a61487977da02f38c7430d23e01b7e5d/examples/C%2B%2B/DDS/HelloWorldExampleSharedMem/HelloWorldPublisher.cpp#L64)), what does it mean? how fast-DDS treat 2 transport protocols for the same topic? will he write it to a shared memory and set to a UDP port on the same time? What happen if we drop the UDP addition, will it still work using shared memory only?
2. On the Zero Copy example there is no adding shared memory transport layer.
should I assume it use shared memory inside Fast-DDS?
3. Is Fast-CDR a mandatory dependency of fast-DDS? I see the examples use it.(I am trying to find out if I can use a thin package of Fast-DDS as possible)

Thanks!

**Comment by EduPonz** [comment]
Hi @Nir-Az ,

I've re-opened your issue until your doubts are solved:


> 1. I see that on the DDS shared memory example not only shared memory transport layer is used, but also UDP ([here](https://github.com/eProsima/Fast-DDS/blob/fc4fade0a61487977da02f38c7430d23e01b7e5d/examples/C%2B%2B/DDS/HelloWorldExampleSharedMem/HelloWorldPublisher.cpp#L64)), what does it mean? how fast-DDS treat 2 transport protocols for the same topic? will he write it to a shared memory and set to a UDP port on the same time? What happen if we drop the UDP addition, will it still work using shared memory only?

The UDP transport is actually not needed there. I spotted it a few weeks ago and have a plan to remove it at some point. In any case, having several transports enables the participant to use one or the other depending on which transport is the remote using. If two participants have UDP and TCP transports, they will communicate over both of them (duplicating data). However, in the case of shared memory (SHM), if a participant detects that it can communicate with another one using SHM, it will only use SHM regardless of the other transports. In this case, SHM only will be fine.

> 2\. On the Zero Copy example there is no adding shared memory transport layer.
>     should I assume it use shared memory inside Fast-DDS?

You are partially correct. By default, Fast DDS enables both a SHM and a UDP transport for every participant (see [this](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/transport.html#transport-layer) and [this](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/eprosimaExtensions.html#transportconfigqos)). However, the Zero-copy example uses a different delivery mechanism for user data traffic; i.e. [DataSharing](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/datasharing.html).

> 3\. Is Fast-CDR a mandatory dependency of fast-DDS? I see the examples use it.(I am trying to find out if I can use a thin package of Fast-DDS as possible)
I'm afraid it is. It become so with the addition of dynamic types. It is actually not necessary to operate normally, since you could implement your own [TopicDataType](https://github.com/eProsima/Fast-DDS/blob/master/include/fastdds/dds/topic/TopicDataType.hpp), but you'd need Fast CDR to be able to build Fast DDS

**Comment by Nir-Az** [comment]
Thanks again, your answers save me a lot of time of investigating the library 😀

I understand your answers regarding 1 & 3.
Regarding 2 I just want to ask if zero copy must be uses at the same method the example use?
DataSharing?
There is no zero copy capability option using the flow of the shared memory example?
There is no mention of shared memory inside the zero copy example.

Thanks again 
Nir

**Comment by EduPonz** [comment]
Hi @Nir-Az ,

There are several things to unwrap here. I have added a few links, and I'd also recommend reading [this article](https://www.eprosima.com/index.php/company-all/news/186-fast-dds-now-with-zero-copy):

* [SHM](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/shared_memory/shared_memory.html) is a transport which uses shared memory (see figure [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/transport.html)). That means that data transmitted using SHM must be encapsulated and copied over from the datawriter's history into the shared memory buffer (much as if it was a UDP socket), and then from there to the datareader's history (de-encapsulating it).
* [Data sharing](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/datasharing.html#) is a shared memory based delivery mechanism; it is not a fully qualified transport. The advantage of it is that, if some [requirements](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/datasharing.html#constraints) are met, the transport encapsulation and the copies to and from the shared memory buffer can be avoided. This is achieved by storing the datawriters history directly into the shared memory segment, from which the datareaders can read directly.
* Datawriters can [loan samples](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/publisher/dataWriter/publishingData.html#borrowing-a-data-buffer) to the application so that it can write its data directly into the datawriter's history (as opposed to normal operation in which the application creates a sample which is then copied into the datawriter's history when calling to `write()`).
* Datareaders can also [loan samples](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/subscriber/dataReader/readingData.html#loaning-and-returning-data-and-sampleinfo-sequences). This means that the application reads directly form the datareader's history instead of getting a copy of the sample.
* [Zero copy](https://fast-dds.docs.eprosima.com/en/latest/fastdds/use_cases/zero_copy/zero_copy.html#), is a combination of data sharing and sample loaning in both datawriter and datareader. Using this approach, and application would write its data directly into the datawriter's history, which is located in a shared memory segment from which the receiving application will read directly, as the sample read is a loan of the datareader's history, which contains references to that same shared memory segment.

The Zero-Copy example does use shared memory, since it uses the data sharing delivery mechanism. There is no mention of it because the library detects when data sharing is available, and uses it by default when it can.
Keep in mind that the Fast DDS examples are meant to show one key functionality at a time, but that does not mean those functionalities cannot be combined in different ways.

**Comment by Nir-Az** [comment]
Thanks again for all of the useful info, I think I got it now :).
I will close this ticket and start working with it and see how it goes.

Much appreciated.

Nir

**Comment by Nir-Az** [comment]
Hi again @EduPonz ,

Correct me if I'm wrong.
[SharedMem](https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B/DDS/HelloWorldExampleSharedMem) example might also use data sharing right?
The domain name is equal, the default value for data sharing is AUTOMATIC by default (`DataSharingKind kind_ = AUTO;`)
So it could use data sharing and the only different from this example to the ZeroCopy example is using the `loan` API for zero copy between the user and the transport layer?

Or using explicitly `std::make_shared<SharedMemTransportDescriptor>();` cancel the data sharing protocol?

**Comment by EduPonz** [comment]
Hi @Nir-Az ,

So a `DataWriter`/`DataReader` is considered data sharing compatible whenever it meets the following requirements (see [this](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/datasharing.html#constraints)):

* It has access to the same shared memory.
* The Topic has a bounded `TopicDataType`, i.e., its `is_bounded()` member function returns true.
* The Topic is not keyed.
* It is configured with `PREALLOCATED_MEMORY_MODE` (default) or `PREALLOCATED_WITH_REALLOC_MEMORY_MODE`.

They key point here is that the type has to be bounded, i.e. it does not contain any type which can increase size indefinitely. This means that all the collections within the type must have a maximum size. For each type, the type support has a class which inherits from `TopicDataType`. If the type support has been generated using Fast DDS-Gen, the class name would typically be `<type_name>PubSubType`.

In the case of data sharing example, this `TopicDataType` derived class is:

https://github.com/eProsima/Fast-DDS/blob/71d986f16f1e6b8a2bb86a85c6c86d1f7f9532d5/examples/C%2B%2B/DDS/HelloWorldExampleDataSharing/HelloWorldPubSubTypes.h#L39

Looking at the implementation of the `is_bounded()` member function, you'll find that it returns `true`. This means, that a `DataWriter`/`DataReader` using this type can use data sharing (given that the rest of the requirements are also met):

https://github.com/eProsima/Fast-DDS/blob/71d986f16f1e6b8a2bb86a85c6c86d1f7f9532d5/examples/C%2B%2B/DDS/HelloWorldExampleDataSharing/HelloWorldPubSubTypes.cxx#L153-L156

Now, if we take a look at the shared memory example `TopicDataType` [derived class](https://github.com/eProsima/Fast-DDS/blob/master/examples/C%2B%2B/DDS/HelloWorldExampleSharedMem/HelloWorldPubSubTypes.h#L39-L55), we'll see that the `is_bounded()` member is not even implemented, meaning that any `DataWriter`/`DataReader` using this type cannot use data sharing. Whether the `is_bounded()` method exists in the derived class is governed by the following `#define`. If the `#define` is not present, then the type is treated as unbounded:

https://github.com/eProsima/Fast-DDS/blob/71d986f16f1e6b8a2bb86a85c6c86d1f7f9532d5/include/fastdds/dds/topic/TopicDataType.hpp#L31-L32

If you look closely at the IDL files ([shm](https://github.com/eProsima/Fast-DDS/blob/master/examples/C%2B%2B/DDS/HelloWorldExampleSharedMem/HelloWorld.idl) and [data sharing](https://github.com/eProsima/Fast-DDS/blob/master/examples/C%2B%2B/DDS/HelloWorldExampleDataSharing/HelloWorld.idl)), you'll see that they both contain a `string`, which in principle is unbounded. In fact, if you use Fast DDS-Gen to generate a type support for these files, you'll see that the `is_bounded()` member function would return `false` for both of them. In the Data Sharing example, we changed the code of the generated type support so that it returns `true`. This works because Fast DDS reserves 255 characters for every `string`, so the data sharing mechanism assumes that this is the size of the data. However, this will make the example fail if the string is long enough (you could actually modify the message to see it). Doing this is definitely not recommended in real applications, and in fact we should update our example so that the data sharing IDL uses a `char[255]` instead of a `string`.

Lastly, regarding the loaning API, we use a similar approach where a `#define` is checked to see whether a `is_plain()` member function is defined:

https://github.com/eProsima/Fast-DDS/blob/71d986f16f1e6b8a2bb86a85c6c86d1f7f9532d5/include/fastdds/dds/topic/TopicDataType.hpp#L34-L35

https://github.com/eProsima/Fast-DDS/blob/71d986f16f1e6b8a2bb86a85c6c86d1f7f9532d5/include/fastdds/dds/topic/TopicDataType.hpp#L289-L292

You can take a look at the Zero Copy example to see both the `is_bounded()` and `is_plain()` member functions in action:

https://github.com/eProsima/Fast-DDS/blob/71d986f16f1e6b8a2bb86a85c6c86d1f7f9532d5/examples/C%2B%2B/DDS/ZeroCopyExample/LoanableHelloWorldPubSubTypes.h#L70-L94

**Comment by Nir-Az** [comment]
@EduPonz Wow, what a great explanation!
Like 👍
