### ISSUE TITLE
 [13356] DDSZeroCopyExample multiple readers

### ISSUE THREAD

**Issue by Nir-Az** [eProsima/Fast-DDS#2369]
Hi,
I am trying to understand the single writer multiple readers configuration.
I took "DDSZeroCopyExample" example and ran 1 publisher and 2 subscribers.
I was expecting to see the same data address for the same index for both readers since data sharing + zero copy are used at this example.

What I saw was different addresses..
Any reason why?
What will be the trigger for deleting this item? When will the publisher override it with new data item?

Thanks,
Nir

**Comment by MiguelCompany** [comment]
> What I saw was different addresses..
> Any reason why?

What you see are different virtual addresses. I use [this tool](https://github.com/katsuster/virt2phys) to check they are the same address

> What will be the trigger for deleting this item? When will the publisher override it with new data item?

As explained in [this section](https://fast-dds.docs.eprosima.com/en/latest/fastdds/use_cases/zero_copy/zero_copy.html#datawriter) of the documentation, samples will be overwritten after writing `resource_limits().max_samples + resource_limits().extra_samples` times.

You can use method `is_sample_valid` on the `DataReader` to check if a sample has been overwritten.

**Comment by Nir-Az** [comment]
Nice!

nir-az-vm@ubuntu:~/Work/git/virt2phys$ sudo ./src/v2p 57649  0x7fffed6671cc 0x4000
pid: 57649:
 virt:0x7fffed667000, phys:0xa6b59000

nir-az-vm@ubuntu:~/Work/git/virt2phys$ sudo ./src/v2p 57544  0x7f42280831d0  0x4000
pid: 57544:
 virt:0x7f4228083000, phys:0xa6b59000

another question..

1. What is the relationship between setting the history depth and max_samples/ extra_samples?
I see a default value of max_samples(5000), does it mean that if I have a topic that contains a 2 [MB] buffer, the writer/reader will allocate 5000* 2 [MB] of memory?

Thanks

**Comment by MiguelBarro** [comment]
> 1. What is the relationship between setting the history depth and max_samples/ extra_samples?

The DDS standard specifies that that `HISTORY depth` and `RESOURCE LIMITS` values must be compatible. In order to
simplify the set up Fast-DDS avoids incompatibilities by making `HISTORY` settings override `RESOURCE_LIMITS` ones.

This gets done in
https://github.com/eProsima/Fast-DDS/blob/ecb9711cf2b9bcc608de7d45fc36d3a653d3bf05/src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp#L50-L59
where `ResourceLimitsQosPolicy::allocated_samples` and `max_samples` values are recalculated according to
`HistoryQosPolicy::depth` and `ResourceLimitsQosPolicy::max_instances` values.

In the DataWriter of the DDSZeroCopyExample example:
```
    DataWriterQos wqos = publisher_->get_default_datawriter_qos();
    wqos.history().depth = 10;
```
where the default value for `ResourceLimitsQosPolicy::max_instances` is 10. The corrected values are then:
```
    ResourceLimitsQosPolicy::max_samples = 10 * 10 = 100
    ResourceLimitsQosPolicy::allocated_samples = min(100, 100) = 100
```
Thus, in this example 100 samples will be allocated for the DataWriter.

> I created an example when I set the publisher to allocate only on 1 sample

in your example 10 samples will be allocated on both Endpoints ( depth = 1 X instances = 10). 

> I expected the writer to fail on `writer_->loan_sample(sample)` but it never fail.

It doesn't fail because the DataWriter is updating the content of it's history sample which is the one referenced by the
DataReaders using shared memory.

It's counterintuitive but a DataReader `take` or `read` will not block the sample contents until the `return_load`
method is called. There is a [DataReader::is_sample_valid](https://fast-dds.docs.eprosima.com/en/v2.5.0/fastdds/api_reference/dds_pim/subscriber/datareader.html?highlight=is_sample_valid#_CPPv4NK8eprosima7fastdds3dds10DataReader15is_sample_validEPKvPK10SampleInfo)  
method that can be use to check if the retrieved sample has been replaced. Your example should go:

```
while (ReturnCode_t::RETCODE_OK == reader->take(data, infos))
{
    // execute some operation with the data without commiting it
    std::this_thread::sleep_for(std::chrono::seconds(1));

    if (infos[0].valid_data && reader->is_sample_valid(&data[0], &infos[0]))
    {
        // the operation was done over valid data, commit it
    }

    reader->return_loan(data, infos);
}
```
Hope I brough some ligh.

**Comment by Nir-Az** [comment]
@MiguelBarro Thanks for explaining, I wasn't aware of max_instances and the Fast-DDS override logic, I will dive in.

Also you may have missed question 2, regarding RELIABLE_RELIABILITY_QOS \ BEST_EFFORT_RELIABILITY_QOS setting.

But currently it's more important for me to understand my example behavior.
It I use your advise and use the `reader->is_sample_valid`, it doesn't say that inside the if block the data will still be valid right (there is no mutex)?, I can get inside with a valid data and the data will be overidden while I spend time there..

We are using data-sharing + zero copy meaning that when the writer loan a sample it will write on the same addresses being read by the reader right (If I use max_instances=1)?

Since I need 1 publisher to distribute images and several subscribers at different rates to read it, (but return before the frame rate duration) I am looking for a minimal memory , runtime efficient configuration that will keep the data safe.
If 1 of my readers will delay the loan for too longI'm fine with the write to fail on loaning samples, that's how I will detect design errors on my application.
But the worst thing that can happen is that it will write on the same data my reader is reading..

If you can shed some light on how to reach this behavior It will help a lot, I got lost with all the possible QOS configuration possibilities..
Thanks mate 🥇

**Comment by MiguelBarro** [comment]
I will try to do my best:

> 2. Does shared memory (data sharing) use the RELIABLE_RELIABILITY_QOS \ BEST_EFFORT_RELIABILITY_QOS setting?
 If yes how does it work? it's rewriting the data to the shared memory if the user didn't read it and it was overridden ?

The relationship is explained [here](https://fast-dds.docs.eprosima.com/en/v2.5.0/fastdds/transport/datasharing.html#blocking-reuse-of-samples-until-acknowledged). Let's elaborate a little:

If the *DataWriter* is `KEEP_LAST` and replaces a sample, the reliability mechanism will notify all matched *DataReaders* that this sample is lost (via RTPS **HEARBEAT** submessage).

A *DataReader* succeeds on read or take a sample only if it is already in it's *DataReaderHistory*. Once a sample reaches *DataReaderHistory* the reliability mechanism acknowledges (via RTPS **ACKNACK** submessage) and disengages because the sample has been successfully delivered. If a *DataReaderHistory* has not received a sample reported as lost by the *DataWriter* the reliability mechanism disengages too, that is, the *DataReader* will not ask for the lost sample again.

This is the DDS expected behavior. But there are caveats using data sharing. Data sharing means matched endpoints effectively use the same samples pool. Thus, if a *DataReader* reads or takes a sample, it references a sample that may be reused by the *DataWriter*.

In order to improve the situation on high publishing rate scenarios with `RELIABLE_RELIABILITY_QOS` the *DataWriter*will block if none of the pool samples is *acknowledged* for `max_blocking_time`. This way the DDS reliability mechanism only guarantees that a sample was valid when it was read or taken.

> But currently it's more important for me to understand my example behavior.

Data sharing use case is focused on large samples that, on CPU time, are more expensive to copy than to process. Let's
revisit the example code:
```
while (ReturnCode_t::RETCODE_OK == reader->take(data, infos))
{
    // 1. Execute some operation with the data without commiting it
    std::this_thread::sleep_for(std::chrono::seconds(1));

    if (infos[0].valid_data && reader->is_sample_valid(&data[0], &infos[0]))
    {
        // 2. the operation was done over valid data, commit it
    }

    reader->return_loan(data, infos);
}
```
Once the sample is taken we have no guarantee at all it has not been replaced already. That's why in point 1 is said to undertake operations over the data but not *commit* yet, that is, don't trust the operation result.

When processing ends `is_sample_valid` method allows us to check if the operation result can be trusted. If no replacement was done we can *commit* the result, that is, use it confidently for whatever purpose.

This is a poor example because the operation is lengthy (1s) and surely the sample will have been replaced if the publication rate (30 Hz) is high.

Which QoS can be modified to prevent this? Several but all imply trade-offs:

+ Setting **ReliabilityQosPolicy** to `RELIABLE_RELIABILITY_QOS` prevents replacing at the expense of blocking for `max_blocking_time` if no samples are available. The `ResourceLimitsQosPolicy::extra_samples` can provide a buffer but its size must take into account the number of *DataReaders*, in order to make it effective.
      
+ Disabling data sharing to fall back to the ordinary DDS behavior. It doesn't mean avoiding using shared memory because the shared memory transport will take over. The caveat is that using shared memory transport the *DataReaderHistories* keep copies of the original *DataWriter* sample (no longer zero-copy).

+ Discretionary use of copies. This comes in handy when the operation is not of a fixed length. When the operation gets slower many samples will be replaced. If the operation fails several times we may replace it with: *local copy, validation, operation* sequence. This approach will work if the copy is faster than the lengthy operation.

  Note that Data Sharing introduces a trade-off between data management efficiency and complexity.

I am afraid zero-copy awareness requires some DDS knowledge to make sense.

**Comment by Nir-Az** [comment]
Thanks the only option for me to make it work and integrate in our project is to make it work with zero copy performance while it is protected against overrides.

Regarding `Setting ReliabilityQosPolicy to RELIABLE_RELIABILITY_QOS`

I did some tests and I am not sure what is going on under the hood.
I am not sure what is the meaning to assign a different policy to the reader and writer..
If the writer wants ack replys, there is no reason for the reader to be set with best effort and not sending it.
Can you explain about some reason to mismatch the settings?

I do see some different behavior when they are set differently. 

On all configurations I get `is_sample_valid() = false`
```
  while (ReturnCode_t::RETCODE_OK == reader->take(data, infos, 1))
    {
        if (infos[0].valid_data)
        {
            if (!reader->is_sample_valid(&data[0], &infos[0]))
               std::cout "Corrupted data found!" << std::endl;
 ...
```

1. Config: 
   Writer = no delay,  Reader = no delay 
   Writer ReliabilityQosPolicy =RELIABLE_RELIABILITY_QOS
    Reader ReliabilityQosPolicy =BEST_EFFORT_RELIABILITY_QOS
   Depth = 10
    extra_samples=0
What I saw was that :
* Time from before write on writer to read on reader is great
* Reader sample data gets override by writer
* Like on all tests reader->is_sample_valid() = false

2. Config: 
   Writer = no delay,  Reader = no delay 
   Writer ReliabilityQosPolicy =RELIABLE_RELIABILITY_QOS
    Reader ReliabilityQosPolicy =RELIABLE_RELIABILITY_QOS
   Depth = 10
extra_samples=0
What I saw was that :
* Time from before write on writer to read on reader became higher than BEST_EFFORT_RELIABILITY_QOS on both
* If I add a slow reader (with a sleep between take and return_loan), the writer start failing on `loan_sample()` , meaning I have 2 readers, 1 is doing nothing and 1 is sleeping a sec with the sample
* Like on all tests reader->is_sample_valid() = false
* Reader sample data gets override by writer

3. Config: 
   Writer = no delay,  2 Readers = 1 slow + 1 fast 
   Writer ReliabilityQosPolicy =RELIABLE_RELIABILITY_QOS
    Reader ReliabilityQosPolicy =RELIABLE_RELIABILITY_QOS
   Depth = 10
extra_samples=2
What I saw was that :
* Time from before write on writer to read on reader became higher than BEST_EFFORT_RELIABILITY_QOS on both
* Like on all tests reader->is_sample_valid() = false


So I guess option 3 is on the track for our purpose..
So the conclusion is work with RELIABLE_RELIABILITY_QOS on both sides and increase `extra_sample` by the number of readers.

Still he questions are:
1. Why `reader->is_sample_valid() = false`?
2. Is there another flow that will not cause a decreased performance like the RELIABLE_RELIABILITY_QOS  do?
3. Is there a solution that will work without hardcoding the readers count as extra_samples? it will cause our SW to be less plug and play..

Thanks
Nir

**Comment by MiguelBarro** [comment]
> I am not sure what is the meaning to assign a different policy to the reader and writer..
> If the writer wants ack replies, there is no reason for the reader to be set with best effort and not sending it.
> Can you explain about some reason to mismatch the settings?

It's a misunderstanding. When I talked about setting **ReliabilityQosPolicy** to `RELIABLE_RELIABILITY_QOS` I meant both endpoints: the *DataReader* and the *DataWriter*. Otherwise, it will not be a reliable exchange.

The only sensical config is the third one. But when I said taken into account the number of *DataReaders* to set the `extra_samples` I didn't mean to add one extra sample per reader. The number of extra samples (sample buffer size) depends on many parameters: publication rates, *DataReaders* processing rates, network bandwidth, ...

The usual approach is to iterate over the sample buffer size using a single *DataReader* till the buffer is large enough to prevent sample overlapped (in a steady state). Once we found the extra samples suitable for a single *DataReader*, having several ones means increasing the sample buffer in the same proportion. Nevertheless:

    + note that we are dealing with *DataReaders* on different machines, on the same machine the CPU availability may be reduced and the consequent delay depletes the buffer. 

    + The *DataWriter* publication rate cannot exceed each *DataReader* processing rate. If that's so no `extra_samples` value will prevent eventually sample overlapping. 

Altering the `depth` is not a great idea. The `depth` must be set according to the use case requirements and not for providing a sample buffer (that's why `extra samples` was introduced). 

For example: in sound industrial practice only the last value of a sensor measurement is control-meaningful. In this case, the `depth` should be one, that is, we discard systematically the preceding sample.

If we make both endpoints `RELIABLE_RELIABILITY_QOS` and provide a suitable `extra samples` value the *DataReaders* will succeed in taking the last measurement update available.

If instead of adding `extra_samples` we increase the `depth` the *DataReaders* will process not the latest sample but the `depth` last ones. This will:

    - Increase by `depth` the numbers of samples to process when the only significant was the last one.
  
    - Don't prevent the sample overlapping because the samples in the *DataWriter history* will be replaced as soon as they are *acknowledged*. Leaving no room for processing time on the *DataReader* side.

> 1. Why `reader->is_sample_valid() = false`?

The `read` or `take` operation returns a collection of `SampleInfo`s that qualifies the *data* collection return. Each `SampleInfo` contains the `SequenceNumber_t` of the associated data. This number is a key for the *DataWriter* sample collection.

The `is_sample_valid` method compares the sequence number on the `SampleInfo` (which is a copy and cannot change) and the retrieved sample (that may be overlapped). If both are equal the sample has not been tampered with.

I've been doing some testing and have verified that the `SampleInfo` sequence number is right but the one retrieve from the actual *data* isn't. This second sequence number is not in the user data but on a inner header that precedes it (`PayloadNode`) and is wrong. We will try to fix this as soon as possible. 

> 2. Is there another flow that will not cause a decreased performance like the RELIABLE_RELIABILITY_QOS  do?
> I used to see ~160 [us] with picks of ~900 [us] deliver time, now I get  ~400 [us] with picks of 4000 [us]

Reliability always comes with a performance hit. Again it depends on the use case. If you are only interest in the last sample as in the example above. If the processing time doesn't exceed the publication period many of the samples won't be overlapped and ignoring the overlapped ones your app can achieve better performance. 

> 3. Is there a solution that will work without hardcoding the readers count as extra_samples? it will cause our SW to be less plug and play..

The magic wand, silver bullet ... there have been workarounds since this industry origins.
Those workarounds rely heavily on each application behavior. For example:

    - having specific settings for specific use cases.
    - develop heuristics associated with key application settings.
    - allow the user to get recommended settings through an automatic testing feature.
    - a hotline.

**Comment by Nir-Az** [comment]
So regarding `is_sample_valid()`,
the reader get a collection of all samples in the shared memory?
or a collection of all the unread sample the writer has written?
what is the input collection stands for?
meaning that the reader cannot use `take_next_sample()` API? because the return loan needs to return a collection?

On the ZeroCopy example the writer writes 1 sample each time on demand... so he cannot override the data if I am not pressing "y" and still in the reader `is_sample_valid()` return false, why is that?

**Comment by MiguelBarro** [comment]
A bugfix is available for the `is_sample_valid` issue on https://github.com/eProsima/Fast-DDS/pull/2382
The DDSZeroCopyExample now includes this API to check sample validity.

> Why is the reason of setting these defaults on Fast-DDS
> Writer reliability `RELIABLE_RELIABILITY_QOS`
> Reader `BEST_EFFORT_RELIABILITY_QOS`?

The [DDS Standard](https://www.omg.org/spec/DDS/1.4/PDF) fixes this default values in section 2.2.3. It beats me too.

> I tried reading the loanable sequence documentation again and I am not sure I understand what does the sequence means..

Again this is a concept introduced by the DDS standard to service the new signature of the read and take operations (2.2.2.5.3.8 & .9). This operations require now the amount of samples to retrieve and allow filtering criteria for the samples. Besides, the standard requires the ability to loan samples using these sequences that must be eventually returned to the *DataReaders* using a specific API (return_loan 2.2.2.5.3.20).

Fast-DDS sequences reference samples in the *DataReaderHistory*. Not all samples but those specified in the arguments of the method that provides the sequence. If the *DataReader* is matched with a *DataWriter* data sharing-friendly, the actual data would be in shared memory and both endpoints histories will reference the same, though it's a specific case.

Most applications will run on different machines where actual network transport would be used instead of shared memory. Others applications run in a single process where intraprocess will be used instead of shared memory. In those cases the sequence returned will completely be owned by the *DataReader*.

The new signatures are inconvenient if we are interested in a single sample, but it has an advantage over `take_next_instance`. `take_next_instance` will copy the sample from the *DataReaderHistory* to a user-provided buffer, though it is no longer required to `return_loan` because no loan took place.

> About the extra_samples, if I got 1 writer that publishes data at 10 HZ and 1 reader that pend for data and process it at 1 HZ
> I get data override even if I set the extra_samples to 100

As I mentioned above:

> The *DataWriter* publication rate cannot exceed each *DataReader* processing rate. If that's so no `extra_samples`
> value will prevent eventually sample overlapping. 

Thus, with a publication rate one order of magnitude above the processing rate eventually overlapping will take place.

> On this behavior the write -> read latency increased from ~160 [us] to ~50 [ms].

Surely due to a wait driven by the settings. Using `BEST_EFFORT_RELIABILITY_QOS`, `KEEP_LAST_HISTORY_QOS` and `depth=1` in both endpoints should prevent any latency.

> If I close the data writer process the reader keeps reading (with no overruns..)

Killing the writer process doesn't remove the shared memory files where the sample data resides. The *DataReader* can take the remaining history data confidently in that situation. In your scenario, it seems the *DataReader* depth is 10 allowing 10 samples to be taken.

> So far I find it hard to understand how this behavior can be configured..

Use as *Qos* in both endpoints `KEEP_LAST_HISTORY_QOS`, `depth=1` and `qos.resource_limits().max_instances=1`. That should grant you the output you are expecting in fast and slow **DataReaders**.  

> This logic does not help the reader to get the data, the user didn't have a chance to process the data before the
> writer is free to reuse it..
> There must be some kind of configuration that allow data integrity using data sharing, BEST_EFFORT mean losing samples,
> not getting corrupted data.  If an application was built using a BEST_EFFORT approach it can make sure the design is
> good enough not to lose any samples,

As mentioned above it depends on the use case. There are applications where speed justifies more message management complexity. Other applications may simplify processing by disabling data sharing and allowing extra copies that don't suppose a performance hit for them. As I mentioned before, disabling data sharing doesn't mean stopping using shared memory.

> The acknowledge is done when the user call read() / take() right? this logic make sense if it was triggered on return_loan()

Nope. The acknowledgment process is independent of user interaction. The *DataReader* acknowledges a message as soon as it receives it. The `read()` or `take()` operation just retrieves data from the *DataReaderHistory* which may have been overlapped (that is the purpose of `is_sample_valid`).

**Comment by Nir-Az** [comment]
Thanks for the bug fix.

>Surely due to a wait driven by the settings. Using BEST_EFFORT_RELIABILITY_QOS, KEEP_LAST_HISTORY_QOS and depth=1 in both endpoints should prevent any latency.

I tried it and still I get an increasing latency each sample, I it keep increasing until a data override is detected

Here you can see my example:
https://github.com/Nir-Az/Fast-DDS-Demo/tree/development/Examples/HelloDDS_Slow_Reader/src

Maybe I did some QOS conflicts that I am not aware of..

I run 1 publisher and 1 slow reader and this is what I see.

![image](https://user-images.githubusercontent.com/64067618/147738568-20bf76cc-a408-4e4e-ba66-46105498859a.png)

Currently this is the major bottleneck of my demo.
My motivation is use micro-services approach on top of a single application, I must set Fast-DDS to allow safe + minimal latency in order to achieve it.

I tested Shared-memory transport and I got ~4 [ms] latency which is too much for our use-case.
with data-sharing  + zero copy I got ~ 160 [us] which is much more reasonable, just need to make it safe :)

I really appreciate your help and looking forward to every reply as it keeps me going with the development.

**Comment by MiguelBarro** [comment]
I've adapt your code to test it.  The actual sources are [here](https://gist.github.com/MiguelBarro/225e220a5f221f3c50876240b94a49d6).
The results were the expected ones:

```
>.\DDSZeroCopyExample.exe publisher 

...
Preparing sample at address 00000206AAAF019C
Preparing sample at address 00000206AAAF019C
Preparing sample at address 00000206AAAF019C
Preparing sample at address 00000206AAAF019C
Preparing sample at address 00000206AAAF019C
```

The publisher works at 10 Hz and always uses the same memory because the depth is 1.

```
>.\DDSZeroCopyExample.exe subscriber 

...
Sample received (count=57) at address 00000233B53E01A0  index=61 Time Since Published: 695 [us]
Sample received (count=58) at address 00000233B53E01A0  index=62 Time Since Published: 677 [us]
Sample received (count=59) at address 00000233B53E01A0  index=63 Time Since Published: 670 [us]
Sample received (count=60) at address 00000233B53E01A0  index=64 Time Since Published: 677 [us]
Sample received (count=61) at address 00000233B53E01A0  index=65 Time Since Published: 686 [us]
Sample received (count=62) at address 00000233B53E01A0  index=66 Time Since Published: 693 [us]
```

the fast processing subscriber is able to cope with the publishing rate and doesn't miss any sample.

```
>.\DDSZeroCopyExample.exe subscriber slow

...
Slow Sample received (count=11) at address 000001F3DC9401A0  index=48 Time Since Published: 101760 [us]
Sample is not valid after processing!
Slow Sample received (count=12) at address 000001F3DC9401A0  index=53 Time Since Published: 51687 [us]
Sample is not valid after processing!
Slow Sample received (count=13) at address 000001F3DC9401A0  index=57 Time Since Published: 198992 [us]
Sample is not valid after processing!
Slow Sample received (count=14) at address 000001F3DC9401A0  index=62 Time Since Published: 152157 [us]
Sample is not valid after processing!
Slow Sample received (count=15) at address 000001F3DC9401A0  index=66 Time Since Published: 284738 [us]
Sample is not valid after processing!
```

the slow processing (1 second delay) subscriber only gets 1 out of 5 samples. Which makes sense because about 4 samples
can be replaced (200ms*5=1s) while 1 is been processed. Of course the sample is replaced in shared memory during the 1
second wait about 4 times ... as expected.

Note that the slow publisher should make a copy of the sample before processing. This copy can be done by Fast-DDS using
an API that doesn't use sequences like `take_next_sample` or by the user code.

At run time the user code can find out if the processing time justifies making copies checking if too many samples are replaced
during processing. 

By the way, doing the sample processing within a Fast-DDS callback function is a bad practice, especially for long
processing times. My advice is to create a dedicated thread and use [wait sets](https://fast-dds.docs.eprosima.com/en/v2.5.0/fastdds/dds_layer/core/waitsets/waitsets.html?highlight=waitset#readcondition) to awake it.

I've done the testing on the branch (bugfix/13357) which allows me to check sample validity.

**Comment by Nir-Az** [comment]
1. What is the difference between `if (infos[i].valid_data)`  and `reader->is_sample_valid()`?
2. Are you saying that the only way to use FastDDS with a slow reader is to copy the data?
No way to configure it somehow by increasing the writer buffer and managing the data like shared_ptr does? 
"No readers on this sample? Dispose it"
3. How can I guarantee that during the memcpy the data will be valid? (please don't say call `is_sample_valid()` 😀)
4. `read_next_sample()` copies the data from the dataReader history and give me a dedicated buffer (I don't think I read it on the documantation)? Is the memcpy he use is safe? Meaning the writer cannot overrun the data?
5. Let say I dont think I have a slow reader, and while developing someone added some code and now the processing time is too long, how can I protect against it? I would like to see a failure on `writer->loan_sample()` if no empty slots are used..otherwise I will get data overrides and don't know about it
6. Thanks for running my code. I will read and take your advise on the `wait_set`.

**Comment by MiguelBarro** [comment]
> 1. What is the difference between if (infos[i].valid_data) and reader->is_sample_valid()?

`infos[i].valid_data` is filled with the value of `reader->is_sample_valid()` on sample reception.

> 2. Are you saying that the only way to use FastDDS with a slow reader is to copy the data?
>    No way to configure it somehow by increasing the writer buffer and managing the data as shared_ptr does?

You can do it by increasing the writer buffer. I've modified the previous example [here](https://gist.github.com/MiguelBarro/46bfad28f60247f0a837355daa36b386) by:

+ increasing the publisher depth to 6 samples.
+ use a devoted processing thread in the slow subscriber to avoid blocking the callback thread and allow the subscriber to update its history.

This way there is no sample overlapping:

```
>.\DDSZeroCopyExample.exe publisher

...
Preparing sample at address 000001C53728019C
Preparing sample at address 000001C5375232AC
Preparing sample at address 000001C5377C63BC
Preparing sample at address 000001C537A694CC
Preparing sample at address 000001C537D0C5DC
Preparing sample at address 000001C537FAF6EC
Preparing sample at address 000001C53728019C
...
```

Because the depth is 6, the samples are reused 6 times less often. Note in the output that it uses sequentially the 6 different samples. That's because it constantly removes the oldest sample, reusing it for the newest value.

```
>.\DDSZeroCopyExample.exe subscriber

...
Sample received (count=78) at address 000001F6468CF6F0  index=78 Time Since Published: 881 [us]
Sample received (count=79) at address 000001F645BA01A0  index=79 Time Since Published: 478 [us]
Sample received (count=80) at address 000001F645E432B0  index=80 Time Since Published: 856 [us]
Sample received (count=81) at address 000001F6460E63C0  index=81 Time Since Published: 455 [us]
Sample received (count=82) at address 000001F6463894D0  index=82 Time Since Published: 880 [us]
Sample received (count=83) at address 000001F64662C5E0  index=83 Time Since Published: 884 [us]
...
```

As before the fast subscriber is able to cope with the publisher rate. The delay is associated to the time the
Subscriber needs to receive the data sharing notification.

```
>.\DDSZeroCopyExample.exe subscriber slow

...
Slow Sample received at address 0000028CF962F6F0  index=60 Time Since Published: 34206 [us]
Slow Sample received at address 0000028CF90E94D0  index=64 Time Since Published: 190926 [us]
Slow Sample received at address 0000028CF8E463C0  index=69 Time Since Published: 153044 [us]
Slow Sample received at address 0000028CF8BA32B0  index=74 Time Since Published: 80161 [us]
Slow Sample received at address 0000028CF89001A0  index=79 Time Since Published: 28790 [us]
Slow Sample received at address 0000028CF938C5E0  index=83 Time Since Published: 196382 [us]
...
```

Without blocking the callback call (there is no callback in the slow case) the latency keeps constant in time. Because the devoted processing thread is spinning the latency will be below 200 ms (publisher writer period).

This is a poor solution:

+ The publisher now uses 6 times more memory in order to prevent the slow subscriber from doing a single copy.
+ If the slow subscriber gets slower (for example 2s delay) we need to increase the publisher depth further (to 12). Using a copy on the subscriber will prevent this to happen.
+ spinning the processing thread, instead of using [wait sets](https://fast-dds.docs.eprosima.com/en/v2.5.0/fastdds/dds_layer/core/waitsets/waitsets.html?highlight=waitset#readcondition) to process only when data is available is poor practice.

I'm not keen to delve further into design details because the subject of this thread is Fast-DDS issues (like the
`is_sample_valid` one) not consultancy.

> 3. How can I guarantee that during the memcpy the data will be valid? (please don't say call is_sample_valid() 😀)

Data sharing cannot guarantee validity because cannot lock the memory. Using `RELIABLE_RELIABILITY_QOS` as was 
[mention](https://fast-dds.docs.eprosima.com/en/v2.5.0/fastdds/transport/datasharing.html#blocking-reuse-of-samples-until-acknowledged)
above it locks the sample till acknowledgment (takes place in sequence generation). There are two cases:

+ Use a sequence-oriented API like `take`. Overlapping can take place once the sequence is provided.
+ Use a non-sequence-oriented API like `take_next_sample`. The inner copy is overlapped free.

again this option may block (eventually prevent) the publisher's write operation if the readers don't `read` or `take` the
 fast enough. Prevent blocking implies often increasing the publisher's `extra_samples` to cope with the reader's delays.

To guarantee delivery is often better to try the use case with a simpler approach, and I quote from above:

>> Disabling data sharing to fall back to the ordinary DDS behavior. It doesn't mean to avoid using shared memory because
>> the shared memory transport will take over. The caveat is that using shared memory transport the
>> *DataReaderHistories* keep copies of the original *DataWriter* sample (no longer zero-copy).

> 4. Is the memcpy he use is safe? Meaning the writer cannot overrun the data?
> do I need to check the data validity or instance ALIVE or something after I got the copied data?

As explained in the previous answer only using a non-sequence-oriented API on a reliable connection the copy is safe.
Doing the copy on user code is subject to overlapping.

> 5. Let say I don't think I have a slow reader, and while developing someone added some code and now the processing time
> is too long, how can I protect against it? 

As explained in the third answer using reliable connection `loan_sample` will fail if all the publisher writer samples are unacknowledge by some subscribers' reader. 

On `BEST_EFFORT_RELIABILITY_QOS` `loan_sample` will reuse the samples. Any application uncertain of the processing speed must be aware and handle overlapped situations.

> 6. How about the latency on the slow reader? Any reson why the latency jumpt to
>    Time Since Published: 198992 [us]?

That's a consequence of blocking the subscriber's listener callback with long processing as explained in the second answer.

> 7. Thanks for running my code. I will read and take your advise on the wait_set.

It's a very useful feature. Remember that custom user conditions can be added to the *wait sets*.

**Comment by Nir-Az** [comment]
Yeaaahhhh.. :)
I took your advise and used the wait_set mechanism on a dedicated thread and now I start seeing FastDDS behaivior that correspond to the FastDDS / DDS documentation.

Thanks a lot!
I still need to test all suggested API usage and measure the performance but now I understand how it works.
I must say that I would add documentation + comment to the examples since none of the examples use wait_set , I think all are using the listener on_data_available() function.

And really, stalling this function cause undefined behavior, the user will probably won't only do only `std::cout` while cloning this example, so it should say that this function needs to return ASAP otherwise bad things will happen..

I will close this thread since it started spreading all over Fast-DDS (and you were very responsive and patient.. )

The only question I got left now is about:
>As explained in the previous answer only using a non-sequence-oriented API on a reliable connection the copy is safe.
Doing the copy on user code is subject to overlapping.

so `take_next_sample()` while working with `BEST_EFFORT` is unsafe..
The copied data I get can be corrupted?

Thanks

**Comment by MiguelBarro** [comment]
> so `take_next_sample()` while working with BEST_EFFORT is unsafe..
> The copied data I get can be corrupted?
Yes, using `BEST_EFFORT` on one of the endpoints forces to check 'SampleInfo::valid_data' member for the `take_next_sample()` return value.

I agree data sharing is a tricky subject and we should extend the documentation-examples on the subject. That's true, I guess, for all the new features like wait-sets. We will take that into account, but note we must also enforce comprehensive ci testing which is often the priority 😓.

Hope you find a successful setup for your use case!

**Comment by Nir-Az** [comment]
OK, thanks again for all the help, I will consider the alternatives.
Great day :)
