### ISSUE TITLE
can combine type T and TPubSubType of fastrtpsgen? [4486]

### ISSUE THREAD

**Issue by comwise** [eProsima/Fast-DDS#242]
when i used fastrtpsgen tools which can generate *.h and *.cxx file,  but i need to care about two class object  which is "T" and "TPubSubType", can you design one class or serialize and deserialize object to one by other way ,  just like proto, It was not very inconvenient, because i just be care about class T not TPubSubType

**Comment by rsanchez15** [comment]
Hi @comwise,

The fact that the data type class and the class implementing the serialization mechanism are separate allows the independence of both. This way the user can develop his own serialization mechanism or use another one different from the one implemented in Fast CDR. According to these criteria, we have decided that both classes will remain separate and therefore will not be merged.

Since the question has been answered I will close this issue. If you have any further questions, please don't hesitate to reopen it.
