### ISSUE TITLE
Running ROS2 demo nodes with CycloneDDS and FastRTPS

### ISSUE THREAD

**Issue by omertal88** [eProsima/Fast-DDS#2424]
Hello,

I recently came across an issue when tring to run the demo nodes with a combination of both DDS providers.
I tried to run the ROS2 talker node with FastRTPS, and listener node with CycloneDDS.

When I run the talker node first, everything works fine. But when I run the listener node first I am missing the first 4 messages...

I am running on Ubuntu 20.04 with ros2-galactic.

## Expected Behavior
Discovery process should be almost instant, and the listener node should receive all messages sent by the talker node.

## Current Behavior

The listener node only receives messages since the 5th message sent.

## Steps to Reproduce

1. Open a terminal.
2. Source ros2 setup.bash file.
2. run: RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ros2 run demo_nodes_cpp listener
3. Open another terminal
4. Source ros2 setup.bash file.
5. run: RMW_IMPLEMENTATION=rmw_fastrtps_cpp ros2 run demo_nodes_cpp talker

## System information

- Fast-RTPS version:  2.3.4
- OS:  Ubuntu 20.04
- Network interfaces:  wlo1, eth0
                       
- ROS2:  Galactic
        

## Additional context

- This only occurs in reliable QoS.
- Downtime can be reduced if you create a publisher profile which reduces the heartbeat period (though you will still miss the first message no matter what interval you use).

## Additional resources
- Same bug opened on cyclone dds repository: https://github.com/eclipse-cyclonedds/cyclonedds/issues/1110 (where they claimed it fastrtps's issue).

**Comment by jsantiago-eProsima** [comment]
HI @omertal88 , thanks for trying Fast DDS!

I think it’s important to clarify a few points regarding this issue and the observed behavior.

1. Delayed data reception should not be conflated with a slow Discovery. There are many other factors that can be the cause. As it’s shown in this Wireshark capture reproducing your issue, discovery is actually quite fast. In the attached network capture you can see the RTPS traffic generated reproducing the issue. Frames 42 and 49 are the DataReader’s announcement and its corresponding ACKNACK, respectively. Frames 52 and 53 are the DataWriter announcement and it’s ACKNACK by the listener. Frame 61 (around 15 ms after the DataReader announcement) is CycloneDDS’s preemptive ACKNACK requesting the first sample.

2. While the RTPS specification (8.4.2.3 Required RTPS Reader Behavior - [RTPS specification PDF version 2.5](https://www.omg.org/spec/DDSI-RTPS/2.5/PDF), for instance) allows sending an ACKNACK message  (called a preemptive ACKNACK) upon discovery to trigger a HEARTBEAT, it is not clear on the contents of that message, and it is left to the different implementations to decide. Fast DDS and RTI Connext use similar contents. Apparently, CycloneDDS chose a different way of representing this preemptive ACKNACK, which is currently ignored by Fast DDS. It also seems that CycloneDDS is using a non-standard synchronization mechanism using HEARTBEATs and ACKNACKs to ensure the samples it is receiving are correct. Fast DDS is instead trusting that the Writer is sending the correct samples in accordance with the DataReader’s Durability QoS information.

3. Regarding the actual data samples, they are being properly sent (once per second, you can see them starting at frame 74 of the attached capture), but they are ignored by CycloneDDS, who in turn sends back an ACKNACK requesting the first sample again. Since the extra reliability check is causing them to drop the samples, there is not much we can do. Reducing the HEARTBEAT period improves downtime because since Fast DDS is not recognizing CycloneDDS’s preemptive ACKNACK it will wait the specified time to send the first HEARTBEAT. After this, all samples will be shown properly (This HEARTBEAT and ACKNACK can be seen on frames 84 and 85). 

4. Regarding the initial data loss itself, losing the first 4 samples would be roughly equivalent to starting the sender application 4 seconds later. If receiving the first samples is required then, adjusting the QoS setting so data durability is TRANSIENT_LOCAL instead of VOLATILE is the way to go. 

We’ll check if something can be done about this, but as of right now we don’t think there’s anything wrong with Fast DDS’s behavior.

[issue_2424.zip](https://github.com/eProsima/Fast-DDS/files/7939865/issue_2424.zip)

**Comment by omertal88** [comment]
Sounds good.
Thank you for the detailed answer.
