### ISSUE TITLE
Message transporting between x86 and arm64 doesn't work in version 2.4.0 [14269]

### ISSUE THREAD

**Issue by QinChen686** [eProsima/Fast-DDS#2614]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

I tried to pub data in x86 ubuntu platform, and sub data in arm64 linux platform, but failed. And the topic discovery in arm64 also didn't find the pub topic. While data transport between x86 and x86, arm64 and arm64 is ok.

### Current behavior

sub cannot discovery pub

### Steps to reproduce

platform 2.4.0 
x86 pub
arm64 sub

### Fast DDS version/commit

2.4.0

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @QinChen686,

We would need more information in order to help you (the issue template guides you through the information required to be able to reproduce your issue). For instance:

* Which OS are you using in x86 and arm64? You say it is a Linux platform but not the specific one. Currently, Fast DDS officially supports Ubuntu 20.04 as you can see in our [Platform support](https://github.com/eProsima/Fast-DDS/blob/master/PLATFORM_SUPPORT.md#platform-support).
* How are the devices connected? Wifi, Ethernet...? Also, are you able to communicate these two devices using another application or is it only Fast DDS the one that cannot communicate?
* How are you launching Fast DDS? Are you using XML configuration? Could you provide the QoS configuration?
* If you can provide us with a small reproducible example and your use case configuration, we will try to reproduce the issue at our side and see what can be happening.

**Comment by Ichabod-Gong** [comment]
Hi @JLBuenoLopez-eProsima
I compiled and ran the [HelloWorldExample](https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B/HelloWorldExample) on x86 ubuntu20.04 and arm64 respectively.It didn't work too.
cmd:
./HelloWorldExample publisher
./HelloWorldExample subscriber

This problem can be reproduced in v2.4.0 and v2.6.0 versions

> Hi @QinChen686,
> 
> We would need more information in order to help you (the issue template guides you through the information required to be able to reproduce your issue). For instance:
> 
> * Which OS are you using in x86 and arm64? You say it is a Linux platform but not the specific one. Currently, Fast DDS officially supports Ubuntu 20.04 as you can see in our [Platform support](https://github.com/eProsima/Fast-DDS/blob/master/PLATFORM_SUPPORT.md#platform-support).
> * How are the devices connected? Wifi, Ethernet...? Also, are you able to communicate these two devices using another application or is it only Fast DDS the one that cannot communicate?
> * How are you launching Fast DDS? Are you using XML configuration? Could you provide the QoS configuration?
> * If you can provide us with a small reproducible example and your use case configuration, we will try to reproduce the issue at our side and see what can be happening.
> 
> Finally, I am afraid that the support to Fast DDS v2.4.x is almost over. The end of life (EOL) date is just the end of this month (tomorrow) as you can see in our [release support](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md#release-support). I strongly suggest that you upgrade to one of the still supported Fast DDS versions.

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @Ichabod-Gong,

Which is the OS in the arm64 architecture? That specific example (HelloWorldExample) was tested between an Ubuntu 20.04 amd64 (x86-64) laptop and an Ubuntu 20.04 arm64 Raspberry Pi and communication was established correctly.

I am afraid that Ambarella Flexible Linux CV22 is not an officially supported OS, neither AOS 2.0, so I cannot ensure that it works correctly in those platforms. You might consider contacting our [support team](https://github.com/eProsima/Fast-DDS#getting-help) in case you need specific support for these platforms.

**Comment by Ichabod-Gong** [comment]
Hi @JLBuenoLopez-eProsima ，
Thanks for your reply,  It would very appreciated if you could give me some advice how to troubleshoot.

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @Ichabod-Gong,

As it seems that you are having discovery troubles, I suggest you include a [DomainParticipantListener](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/domain/domainParticipantListener/domainParticipantListener.html) with the discovery callbacks implemented. You can also analyze a network traffic capture to see the packets that are actually being sent and received (included the discovery traffic, DATA(p), DATA(r), DATA(w)...). Finally, building with symbols and debugging. Sorry for not being more help.

**Comment by Ichabod-Gong** [comment]
> 
OK I'll try with that.
Thank you

**Comment by JLBuenoLopez-eProsima** [comment]
Original contributor has not provided the required information needed to characterize properly this issue. In the meantime too, [Fast DDS v2.4.2](https://github.com/eProsima/Fast-DDS/releases/tag/v2.4.2) has been released as the last patch release for that minor branch (see [release lifecycle](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md#release-support) for more information). Consequently, I am going to proceed and close this issue due to inactivity according to our contributing guidelines, and also because the Fast DDS version is no longer supported.

Please, feel free to reopen if you reproduce the issue in some other supported Fast DDS version providing at the same time the information required.
