### ISSUE TITLE
Writer -> Reader message is missed if sent immediately after the writer was created [14453]

### ISSUE THREAD

**Issue by Nir-Az** [eProsima/Fast-DDS#2641]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

I have 2 processes (even on the same PC) a writer on a reader.

**Reader side:**
The reader create a datareader and use `wait_for_unread_message()` in a loop
something like this:
```
rqos.history().kind = KEEP_LAST_HISTORY_QOS;
rqos.history().depth = 10;
rqos.reliability().kind = RELIABLE_RELIABILITY_QOS; 
rqos.durability().kind = VOLATILE_DURABILITY_QOS; 
rqos.data_sharing().automatic();                
rqos.ownership().kind = EXCLUSIVE_OWNERSHIP_QOS;

create_reader()..

while ( true )
{
  if( _reader->wait_for_unread_message( { 1, 0 } ) )
      std::cout << "message arrived" << std::endl;
}
```
**Writer side:**
```
Event triggered

DataWriterQos wqos = DATAWRITER_QOS_DEFAULT;
wqos.reliability().kind = RELIABLE_RELIABILITY_QOS;
wqos.durability().kind = VOLATILE_DURABILITY_QOS;
wqos.data_sharing().automatic();
wqos.ownership().kind = EXCLUSIVE_OWNERSHIP_QOS;
create_datawriter(listener)

while ( listener->matched <= 0) sleep (250 ms)
if (data_writer->write( &msg ) ))
    std::cout << "message sent" << std::endl;
```

When I run both processes I expect that the reader will print a `message arrived`  on every `message sent` print on the writer side

### Current behavior

When I run this 2 processes (Windows on the same machine) I see.

The writer don't sleep it gets a reader match before the check and send the message immediately.
The reader sometimes print the " message arrived" and sometimes not.

If I add a sleep (10 ms) between the create_datawriter and the _writer->write()
I always get the message.

Why is that?

I thought once I got a reader match I can send it a message right?
Especially  if the QOS is reliable..

### Steps to reproduce

mentioned above

### Fast DDS version/commit

Release 2.6.0

### Platform/Architecture

Windows 10 Visual Studio 2019

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by jparisu** [comment]
Hi @Nir-Az 

As you are using the VOLATILE QoS policy, the middleware cannot assure that the message will arrive to  the Reader. This could easily occur when you publish (`DataWriter::write` method) just after creating the DataWriter, because it could happen that matching with DataReader takes longer than writing the data, and **a volatile DataWriter only send messages to those DataReaders matched.** 
This is probably the reason why sometimes the message arrives and other don't. Those times that the matching has been faster than the writing, the message will arrive. When you sleep before writing, the matching will probably take place before and thus DataReader will receive the message.

Please, check if this problem occurs using `TRANSIENT_LOCAL_DURABILITY_QOS` in DataWriter and DataReader.

**Comment by Nir-Az** [comment]
Thanks, @jparisu ,
For my topic use case `TRANSIENT_LOCAL_DURABILITY_QOS` does not fit.
I do not wish the reader to receive previous published data.

I was concerned about this case (race between DataReader match and the Writer sending a message) , so I am waiting for the `on_publication_matched` callback before I send the message.

Why does FastDDS call the  `on_publication_matched` before the match occurs? it is causing an undefined behavior IMO, don't you think?

1. I get notified on a match, I send a message and it's not being sent cause we still don't have a match?
2. The DataWriter.write() call returns true meaning the message was sent even if it wasn't?
So I don't have the tools from `FastDDS`  API to  address this use case..

**Comment by jparisu** [comment]
Hi @Nir-Az 

It is not exactly like that. 
The problem here is not that there is an undefined behaviour, but there is a synchronization problem.
The matching is done from DataReader and DataWriter sides independently, and there is not a synchronization method to check this matching has been fulfilled (it does not exist in DDS standard either).
Thus, when DataWriter has matched with DataReader, the callback from listener arises, and then you send the message. At that time, the DataWriter has a matching reader, and so it sends the data. BUT in DataReader side, the matching has not been completed yet, and thus the data arrives, but it is discarded because it comes from a non matching endpoint.

This problem is a DDS standard problem, and could not be fixed but adding a user-level logic to assure the matching has been fulfilled in both sides.
Two workarounds to this issue would be:
- use other QoS that assure the data arrives to the target
- wait before sending the data from writer so DataReader has time to match
Also, this problem only occur using data_sharing / shared_memory / intraprocess communication, because when message has to be sent to the network from DataWriter to DataReader, it would be extremely rare that the data arrives before the matching is completed.

## Summary
It is not a Fast DDS bug, but a DDS standard gap.
DDS does not assure you that your data will arrive to target if QoS is not `TRANSIENT_LOCAL` `RELIABLE`.

## Disambiguation
`write()` in Fast DDS DataWriter does not fail if there is no DataReader matched or if message has not arrive DataReader. It only fails if the data could not be sent.

Matching process is not symmetrical.
The callback ` on_publication_matched` is called when DataWriter has matched with DataReader, but this does not assure that DataReader has matched with DataWriter.

Even when matching is not symmetrical, in most scenarios it could be considered as so, as the discovery is indeed symmetrical: matching process does not occur until both has discovered each other and has notified that discovery has been fulfilled.

**Comment by Nir-Az** [comment]
@jparisu Thanks for the detailed answer.

I understand what you mean.
Sounds like a gap indeed, I will figure something out.

I will close this issue,

Thanks
Nir.
