### ISSUE TITLE
build helloworldexample error in Windows + vscode 

### ISSUE THREAD

**Issue by wsm6636** [eProsima/Fast-DDS#2816]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Compile HelloWorld in vscode

### Current behavior

An error occurred while building

[build] [ 88%] Building CXX object CMakeFiles/HelloWorldExample.dir/HelloWorld_main.cpp.obj
[build] g++.exe: error: /w34101: No such file or directory
[build] g++.exe: error: /w34555: No such file or directory
[build] g++.exe: error: /w34189: No such file or directory
[build] g++.exe: error: /w35038: No such file or directory
[build] g++.exe: error: /w34715: No such file or directory
[build] CMakeFiles\HelloWorldExample.dir\build.make:75: recipe for target 'CMakeFiles/HelloWorldExample.dir/HelloWorld.cxx.obj' failed
[build] mingw32-make.exe[3]: *** [CMakeFiles/HelloWorldExample.dir/HelloWorld.cxx.obj] Error 1
[build] mingw32-make.exe[3]: *** Waiting for unfinished jobs....
[build] g++.exe: error: /w34101: No such file or directory
[build] g++.exe: error: /w34555: No such file or directory
[build] g++.exe: error: /w34189: No such file or directory
[build] g++.exe: error: /w35038: No such file or directory
[build] g++.exe: error: /w34715: No such file or directory
[build] CMakeFiles\HelloWorldExample.dir\build.make:90: recipe for target 'CMakeFiles/HelloWorldExample.dir/HelloWorldPubSubMain.cxx.obj' failed

### Steps to reproduce

cmake tools
build

### Fast DDS version/commit

eProsima_Fast-DDS-2.5.0-Windows

### Platform/Architecture

Windows 10 Visual Studio 2019

### Transport layer

TCPv4

**Comment by MiguelBarro** [comment]
This is a known issue fixed [here](https://github.com/eProsima/Fast-DDS/pull/2509).
Unfortunately, `v2.5.0` lacks this fix. The first version including it is `v.2.6.0`
Nevertheless, the windows installer deploys MSVC-generated libraries that use MSVC CRT & STL implementation. Trying to build the examples with another compiler (gcc or mingw) will lead to crashes due to ABI incompatibilities.
For other compilers in windows is advisable to [build from sources](https://fast-dds.docs.eprosima.com/en/v2.7.0/installation/sources/sources_windows.html).

**Comment by MiguelBarro** [comment]
Closed by lack of feedback. Please reopen if deemed necessary.
