### ISSUE TITLE
Fast DDS removes lock files.

### ISSUE THREAD

**Issue by oleksandr-hryshchuk** [eProsima/Fast-DDS#2975]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Fast DDS should not remove lock files in the /dev/shm directory.

### Current behavior

Fast DDS removes lock files in the /dev/shm directory. This might cause race conditions as described [here](https://unix.stackexchange.com/questions/368159/why-flock-doesnt-clean-the-lock-file).

This is related to the graceful shutdown and the cleanup script provided by Fast DDS.

### Steps to reproduce

I don't have particular steps since this is a design issue.

### Fast DDS version/commit

2.6.0

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by Mario-DL** [comment]
Hi @oleksandr-hryshchuk,

Thanks for the advice. Since FastDDS > 1.10.0, robust conditions were added to solve issues between interprocess shared memory and POSIX glibc 2.25 #1144. Currently, the removal of memory files under /dev/shm is performed safely when the rest of the processes using it have finished as pointed out in the last comment on the forum you posted. I am closing this since it is not an issue.
