### ISSUE TITLE
RTPS_READER_HISTORY Error

### ISSUE THREAD

**Issue by AstraYH** [eProsima/Fast-DDS#3047]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

I want to realize the vector of larger size sending and receiving by using DDS for Python.
The terminal outputs the error.
[RTPS_READER_HISTORY Error] Change payload size of '2692' bytes is larger than the history payload size of '2679' bytes and cannot be resized. -> Function can_change_be_added_nt

### Current behavior

When I used DDS for Python I encountered this problem, the subscriber cannot receive the data from the publisher.
Meanwhile, the terminal outputs an error.
if the size of vector is less than 110, it can work normally, otherwise,it will print error and can't receive message.
Could you give me some good advice, millions of thanks.
![2022-10-27 10-52-35屏幕截图](https://user-images.githubusercontent.com/40078509/198181261-809675cc-1d2d-492f-8669-7683418cf3d8.png)
![2022-10-27 10-52-26屏幕截图](https://user-images.githubusercontent.com/40078509/198181266-7babe434-49b0-403e-92cf-27fdac747ea3.png)
![2022-10-27 10-54-38屏幕截图](https://user-images.githubusercontent.com/40078509/198181356-74dad127-0f9f-4478-b96f-79bc2c59a21e.png)
![2022-10-27 10-54-20屏幕截图](https://user-images.githubusercontent.com/40078509/198181371-0018236f-b9c1-4c04-9e76-dcf7191e8522.png)

### Steps to reproduce

You can reproduce the problem with this demo
[demo.zip](https://github.com/eProsima/Fast-DDS/files/9875464/demo.zip)

### Fast DDS version/commit

Ubuntu: 20.04.5
Fast-DDS: 2.8
python: 3.8.10
swig: 4.0.2

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by jsantiago-eProsima** [comment]
Hi @AstraYH , thanks for using Fast DDS!

The message you are seeing indicates that Fast DDS is using it's default setting for the `MemoryManagementPolicy` (`PREALLOCATED_MEMORY_MODE`). It appears in your reproducer you are setting the `DataReaderQos` properly (with `DYNAMIC_REUSABLE_MEMORY_MODE`) but then those `DataReaderQos` are not used in the actual `create_datareader` call, using `DATAREADER_QOS_DEFAULT` instead. 

Using `rqos` instead of `eprosima::fastdds::dds::DATAREADER_QOS_DEFAULT` allowed me to receive messages with a sequence length of 110 or greater.

**Comment by AstraYH** [comment]
Thanks for your replay, it's very helpful for me!
