### ISSUE TITLE
failed to re-create a participant after a while

### ISSUE THREAD

**Issue by iuhilnehc-ynos** [eProsima/Fast-DDS#3059]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

- re-creating the participant successfully all the time
- the RES showed by `top` command can be steady

### Current behavior

- the test application exits after a while and outputs the log below:

```
Starting 
Calculated port number is too high. Probably the domainId is over 232, there are too much participants created or portBase is too high.
2022-11-03 13:40:51.925 [RTPS Error] Calculated port number is too high. Probably the domainId is over 232, there are too much participants created or portBase is too high. -> Function getUnicastPort
```

if the [participant_id_](https://github.com/eProsima/Fast-DDS/blob/2f2cc5278509d661f91b8af1582116055daa10ad/src/cpp/fastdds/domain/DomainParticipantImpl.cpp#L126) is updated with `29063` by [RTPSDomain::getNewId](https://github.com/eProsima/Fast-DDS/blob/2f2cc5278509d661f91b8af1582116055daa10ad/include/fastdds/rtps/RTPSDomain.h#L326), it leads to getting a wrong port in the [eprosima::fastrtps::rtps::PortParameters::getUnicastPort](https://github.com/eProsima/Fast-DDS/blob/2f2cc5278509d661f91b8af1582116055daa10ad/include/fastdds/rtps/common/PortParameters.h#L95).

- as the application exits abnormally, I am unsure if the memory consumed by the application can be steady finally.
(the RES increases at the very beginning and keeps a steady value for a little while, and continues to increase, ..., and then the application exits.)

### Steps to reproduce

1. patch the https://github.com/eProsima/Fast-DDS/blob/2f2cc5278509d661f91b8af1582116055daa10ad/examples/cpp/dds/HelloWorldExample/HelloWorld_main.cpp to test re-creating a participant. (Sorry about it's not a normal application in the real world.) 

```patch
diff --git a/examples/cpp/dds/HelloWorldExample/HelloWorld_main.cpp b/examples/cpp/dds/HelloWorldExample/HelloWorld_main.cpp
index 35870eb67..9041eddcd 100644
--- a/examples/cpp/dds/HelloWorldExample/HelloWorld_main.cpp
+++ b/examples/cpp/dds/HelloWorldExample/HelloWorld_main.cpp
@@ -19,6 +19,8 @@
 
 #include <limits>
 #include <sstream>
+#include <thread>
+#include <chrono>
 
 #include "HelloWorldPublisher.h"
 #include "HelloWorldSubscriber.h"
@@ -295,6 +297,15 @@ int main(
     {
         case 1:
         {
+            while (true) {
+              HelloWorldPublisher mypub;
+              if (mypub.init(use_environment_qos))
+              {
+
+              }
+              std::this_thread::sleep_for(std::chrono::milliseconds(10));
+            }
+
             HelloWorldPublisher mypub;
             if (mypub.init(use_environment_qos))
             {
```

2. run `./DDSHelloWorldExample publisher`

### Fast DDS version/commit

2f2cc5278509d661f91b8af1582116055daa10ad

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

<del>A node in `ros2` corresponds to one participant of `Fast-DDS`. As `ros2` component_manager application can dynamically load and unload the node, so I think it's a normal case to re-create the participant in one application all the time.</del>

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @iuhilnehc-ynos,

First of all, thanks for your report! There is a misunderstanding in one of your statements. Since ROS 2 Foxy, which is the oldest still alive [ROS 2 distribution](https://docs.ros.org/en/rolling/Releases.html#list-of-distributions), a Context in ROS 2 corresponds to a DDS DomainParticipant as explained in [this ROS 2 design document](https://design.ros2.org/articles/Node_to_Participant_mapping.html). Consequently, if your concern is about loading and unloading nodes in ROS 2, you are not going to reach the upper limit of possible DomainParticipants. For that you would have to be launching in the same process more than 29k ROS 2 Contexts, which is not that common.

Consequently I do not think this is an issue because creating more than 29k DomainParticipants is not a common use case.

Please, consider closing the issue if the answer is satisfactory. If not, please share some more information about your use case so we can propose workarounds and alternative solutions.

**Comment by JLBuenoLopez-eProsima** [comment]
> Do you think it's correct behavior to re-create the DomainParticipant all the time? even if there exists only one DomainParticipant?

It all depends on the needs of your application... Why do you need to remove the DomainParticipant and re-create it? Why do you need to do that more than 29k times? Without specific information is kind of difficult to be of help. You may be interested to contact our [commercial support team](https://github.com/eProsima/Fast-DDS#getting-help) in order to discuss your needs and application requirements.

**Comment by iuhilnehc-ynos** [comment]
The original issue is from https://github.com/ros2/rclpy/issues/1034.

I just want to check if the `rmw_fastrtps_cpp` has the same problem even if the `rmw_cyclonedds_cpp` is specified in the report,  but it seems to be a limitation(sorry, I called it a limitation) about re-creating the `DomainParticipant` in `FastDDS`.

There is no memory leak (confirmed by the `valgrind`) about re-creating the `DomainParticipant` in `FastDDS`, but I am not sure if there is something about global variables or static variables consuming the memory all the time while re-creating the DomainParticipant. That's why I do this test.

Is there a better policy to recycle the DomainParticipant id?

**Comment by JLBuenoLopez-eProsima** [comment]
The DomainParticipant id is an internal counter of Fast DDS that the user cannot modify and it is always incremental with the current implementation. As you stated, this can cause troubles if some application launches (and destroys them or not) more than 29k DomainParticipants which is not something common.

I am afraid I cannot help you with your experiments. But it seems like the test you are running is not the correct one to measure what you want. Sorry.

I consider that we can close this issue as the main point has been discussed and reach an agreement. Would you like to proceed?

**Comment by iuhilnehc-ynos** [comment]
Anyway, thanks for your help.

**Comment by iuhilnehc-ynos** [comment]
FYI: If setting domain_id with 232, there are no 29k times that one application re-creates the participant.

**Comment by JLBuenoLopez-eProsima** [comment]
That's completely true but it is the DDS specification that sets the well-known ports rule. If you look into other vendors you see that the domain id limitation between 0 and 232 is the most common. Again, it is assumed that 232 domains are more than enough for almost every application and if there is a specific need for more it can be discussed how to handle that specific case.
