### ISSUE TITLE
Cannot re-create TCP Participant over three times in an application

### ISSUE THREAD

**Issue by ulongcha** [eProsima/Fast-DDS#3845]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Correct re-create participant in an application.

### Current behavior

It seems like client participant can only discovery three times server participant.
![QQ截图20230913131103](https://github.com/eProsima/Fast-DDS/assets/50707687/982fab76-4866-4792-a135-22c745e9f80b)

### Steps to reproduce

After input 3 times, the client will not discover server participant anymore.

[RebootDemo.zip](https://github.com/eProsima/Fast-DDS/files/12593566/RebootDemo.zip)

### Fast DDS version/commit

V2.8.1

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

TCPv4

### Additional context

The main reason why I want to restart the server participant is that the server's IP may change. Does re-create server participant is needed  when the IP is change?

**Comment by Mario-DL** [comment]
Hello @ulongcha,

Thanks for reporting the issue. Please, could you check if the issue is also reproduced in `Fast DDS v2.11.2` ? Some PR's related with `TCP` have been introduced.
And one more thing, what does it happen if you wait ~25 secs after the third time? It is for discarding that the participant should first lost its liveliness, and unmatched.

**Comment by ulongcha** [comment]
Hi @Mario-DL ,
Sorry for late reply. I've tried the demo on `Fast DDS v2.11.2`, the problem has been solved. Thank you very much!
