### ISSUE TITLE
Fastdds communicates normally when starting the reader writer program. If the network cable is unplugged and reconnected for about 20 seconds at this time, the data sent by the writer will not be received by the reader

### ISSUE THREAD

**Issue by hong12234** [eProsima/Fast-DDS#3903]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Fastdds communicates normally when starting the reader writer program. If the network cable is unplugged and reconnected for about 20 seconds at this time, the data sent by the writer will not be received by the reader。When should communication continue under normal circumstances。

### Current behavior

Fastdds communicates normally when starting the reader writer program. If the network cable is unplugged and reconnected for about 20 seconds at this time, the data sent by the writer will not be received by the reader

### Steps to reproduce

Fastdds communicates normally when starting the reader writer program. If the network cable is unplugged and reconnected for about 20 seconds at this time, the data sent by the writer will not be received by the reader

### Fast DDS version/commit

fastdds 2.1
![image](https://github.com/eProsima/Fast-DDS/assets/38304396/25e6bdf9-0673-4daa-9577-a2bdc235953a)

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

UDPv4

### Additional context

![image](https://github.com/eProsima/Fast-DDS/assets/38304396/0ad5eddf-9f82-49bd-bd61-51084856b0e8)
The configuration of all readers and writers is shown in the above figure

**Comment by JLBuenoLopez-eProsima** [comment]
@hong12234 thanks for your contribution,

In order to help you I think some more info is needed:

1. Can you describe the issue more precisely? Is the communication reestablished at some point but not immediately when the cable is disconnected more than 20 seconds? If you reconnect the cable sooner communication is reestablished?
1. Fast DDS only checks for network interfaces when initialized. If when reconnecting a new IP address is assigned, Fast DDS would not automatically reconnect. You will need to [rescan the network interfaces](https://fast-dds.docs.eprosima.com/en/latest/fastdds/use_cases/dynamic_network_interfaces/dynamic_network_interfaces.html#dynamic-network-interfaces). So please, check if the IP address is the same after reconnection.

**Comment by hong12234** [comment]
Thanks for your reply，When it can be determined, the IP address is the same。I tried overnight and the next day, but I still couldn't establish a connection

**Comment by hong12234** [comment]
What can be confirmed is that my configuration is fine, right？
