### ISSUE TITLE
Zero-Copy communication don't work [19740]

### ISSUE THREAD

**Issue by shiyiyuedeyu** [eProsima/Fast-DDS#3925]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

I am using the zerocopy example. Unlike #3809 ,  I just use int32 in the message struct.  Unfortunately，it didn't work.

### Current behavior

writer_->loan_sample(sample) didn't retutn ReturnCode_t::RETCODE_OK. Besides, TypeSupport::is_plain() return false.

### Steps to reproduce

The struct I defined in the IDL file:
    struct SimpleInfo {
      int32 simple_first;
      int32 simple_second;
      int32 simple_third;
    };
I just use int32 type in this message struct and int32 is one of primitive types.

### Fast DDS version/commit

v2.12.0

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Zero copy

### Additional context

Arm64 server. Ubuntu 22.04

**Comment by EduPonz** [comment]
@shiyiyuedeyu ,

Your issue is that with the new Fast DDS Gen dependency (v3.0.0), the non-final types are not considered plain. This was documented in the corresponding [release notes](https://github.com/eProsima/Fast-DDS-Gen/releases/tag/v3.0.0), which we encourage to read on the [Fast DDS v2.12.0 release notes](https://github.com/eProsima/Fast-DDS/releases/tag/v2.12.0). I have verified that the solution to your problem is using this IDL:

```idl
@final
struct SimpleInfo {
    int32 simple_first;
    int32 simple_second;
    int32 simple_third;
};
```

**Comment by JLBuenoLopez-eProsima** [comment]
@shiyiyuedeyu 

You can also change the default extensibility using the new option `-de | -default-extensibility` when generating your code using Fast DDS-Gen as also explained in [Fast DDS docs](https://fast-dds.docs.eprosima.com/en/latest/fastddsgen/usage/usage.html#supported-options). In this case, instead of modifying your IDL it would be enough to just generate the TypeSupport passing `-de final` to Fast DDS-Gen.

**Comment by shiyiyuedeyu** [comment]
@EduPonz Thanks for your reply. 
By the way, can final type struct which contains other final type struct still be considered plain ? For example: 
@final
struct SimpleInfo {
    int32 simple_first;
    int32 simple_second;
    int32 simple_third;
};

@final
struct MultiInfo {
    SimpleInfo simple_info;
    int32 multi_second;
    int32 multi_third;
};

I use MultiInfo as message struct. it didn't work. Of course, using SimpleInfo as message struct still works.

**Comment by richiware** [comment]
@shiyiyuedeyu 

I've tested your IDL. I used it directly in our ZeroCopyExample, changing the name of MultiInfo structure to "LoanableHelloworld" and several minor changes to make the code compile. And the example works. The publisher can send the "MultiInfo" structure without problems.

Can you send us more detail of the error?

Thanks.

**Comment by JLBuenoLopez-eProsima** [comment]
In this case, if you query the `is_plain` API, it would return that the type is not plain. This is because the described type have a padding after simple_info member and before the multi_second member, so the representation in memory does not correspond to the CDR representation (which is the meaning for a type being plain). You can find more information in:

* eProsima/Fast-DDS-Gen#193

A possible workaround is modifying your data type to include the Header member as the last member of the structure. Otherwise, you have to ensure that the alignment of the latest member of your Header structure matches the alignment of the structure.

I am closing the issue as the main concern has been answered and the underlying issues are duplicated from another thread.
