### ISSUE TITLE
When calling DomainParticipantFactory->create_participant rise an error..

### ISSUE THREAD

**Issue by ugurmelihsurme** [eProsima/Fast-DDS#4079]
The error message mentioned above occurs when the lines below are executed. FastDDS v2.12.1, Visual Studio 2022, CMake 3.28.0-rc5

```
eprosima::fastdds::dds::DomainParticipant *enabled_participant =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->create_participant(1, eprosima::fastdds::dds::PARTICIPANT_QOS_DEFAULT);

```

> Exception has occurred: CPP/std::length_error Unhandled exception at 0x00007FFE1E9FCF19 in testserver.exe: Microsoft C++ exception: std::length_error at memory location 0x00000039857B6010

Could you give me a any advice on it?

**Comment by juanlofer-eprosima** [comment]
Hi @ugurmelihsurme ,

Thanks for your contribution. I'm afraid Visual Studio 2022 is currently not supported (see [platform support](https://github.com/eProsima/Fast-DDS/blob/v2.12.1/PLATFORM_SUPPORT.md)). However, it would be good to know if this issue was already present in previous releases or recently introduced.

**Comment by Mario-DL** [comment]
Hi @ugurmelihsurme 

Thanks for using Fast DDS and for the report.
I am feeling free to close this issue as the platform is not officially supported. If the issue can be reproduced in an [oficially supported platform](https://github.com/eProsima/Fast-DDS/blob/v2.12.1/PLATFORM_SUPPORT.md) please, open an issue in this repository, filling the template and attaching a minimal reproducer.
