### ISSUE TITLE
[21654] The discovery_server example is stucked or deadlock when many readers and writers are matching with tcpv4/reilability.

### ISSUE THREAD

**Issue by chunyisong** [eProsima/Fast-DDS#5235]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

The discover server example should work well when many readers and writers are matching with tcpv4/reilability,and should be closed by Ctrl+C.

### Current behavior

The example can be started but stucked and can not be close by Ctrl+C.

![image](https://github.com/user-attachments/assets/11b2d3fb-d79b-4fef-934a-a5aa83738f64)

### Steps to reproduce

To test discover server performance when many readers and writers are matching,I add simple code to create 1000 differern topics and related (one with per topic ) 1000 writers/readers.
1. Add simple source code only to create 1000 topics/writers/readers for matching test:

```c++
diff --git a/examples/cpp/discovery_server/ClientPublisherApp.cpp b/examples/cpp/discovery_server/ClientPublisherApp.cpp
index 52422d14a..cb05752a0 100644
--- a/examples/cpp/discovery_server/ClientPublisherApp.cpp
+++ b/examples/cpp/discovery_server/ClientPublisherApp.cpp
@@ -209,6 +209,11 @@ ClientPublisherApp::ClientPublisherApp(
     {
         throw std::runtime_error("DataWriter initialization failed");
     }
+    for (int i = 0, n = 1000; i < n; ++i) {
+        const auto& tn = config.topic_name + std::to_string(i);
+        auto topic = participant_->create_topic(tn, type_.get_type_name(), TOPIC_QOS_DEFAULT);
+        assert(publisher_->create_datawriter(topic, wqos, this) != nullptr);
+    }
 }
 
 ClientPublisherApp::~ClientPublisherApp()
diff --git a/examples/cpp/discovery_server/ClientSubscriberApp.cpp b/examples/cpp/discovery_server/ClientSubscriberApp.cpp
index a026455eb..c9b7fcf83 100644
--- a/examples/cpp/discovery_server/ClientSubscriberApp.cpp
+++ b/examples/cpp/discovery_server/ClientSubscriberApp.cpp
@@ -209,6 +209,11 @@ ClientSubscriberApp::ClientSubscriberApp(
     {
         throw std::runtime_error("DataWriter initialization failed");
     }
+    for (int i = 0, n = 1000; i < n; ++i) {
+        const auto& tn = config.topic_name + std::to_string(i);
+        auto topic = participant_->create_topic(tn, type_.get_type_name(), TOPIC_QOS_DEFAULT);
+        assert(subscriber_->create_datareader(topic, rqos, this) != nullptr);
+    }
 }
 
 ClientSubscriberApp::~ClientSubscriberApp()
``` 
2. Open a terminal,start server app: `./discovery_serverd server --transport tcpv4`
3. Open a terminal,start publisher app: `./discovery_serverd publisher --reliable --transport tcpv4`
4. Open a terminal,start subscriber app: `./discovery_serverd subscriber --reliable --transport tcpv4`
5. After a while, all three apps are stucked or deadlock,and Ctrl+C can not kill any app.As top shown in the image above,three apps are no CPU usage,no send/receive log,Ctrl+C failed.

### Fast DDS version/commit

FastDDS v3.0.0

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

TCPv4

**Comment by JesusPoderoso** [comment]
Hi @chunyisong, thanks for the report.
The eProsima Team will review and replicate the issue and come back  with some feedback in the following days.

**Comment by cferreiragonz** [comment]
Hi @chunyisong.
It seems that your TCP sockets are becoming overwhelmed with messages. When running that many writers and readers, the message writing rate is likely exceeding the message processing rate. This causes the socket queues to grow until they reach their maximum size. At that point, communication becomes blocked due to the inherent behavior of TCP transport, which requires available space in the sockets to acknowledge sent messages.

You might consider using the `non_blocking_send` option available in Fast DDS (documentation [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/api_reference/transport/tcp_transport/tcp_transport_descriptor.html#_CPPv4N8eprosima7fastdds4rtps22TCPTransportDescriptor17non_blocking_sendE)). This option prevents new messages from being sent if the sockets are full, helping to avoid the blocking behavior.

You can directly try this approach in your example, just configure it in the TCP Transport descriptor:
```cpp
diff --git a/examples/cpp/discovery_server/ClientPublisherApp.cpp b/examples/cpp/discovery_server/ClientPublisherApp.cpp
index 52422d14a..2a01d1d75 100644
--- a/examples/cpp/discovery_server/ClientPublisherApp.cpp
+++ b/examples/cpp/discovery_server/ClientPublisherApp.cpp
@@ -118,6 +118,7 @@ ClientPublisherApp::ClientPublisherApp(
         {
             auto descriptor_tmp = std::make_shared<eprosima::fastdds::rtps::TCPv4TransportDescriptor>();
             descriptor_tmp->add_listener_port(0);
+            descriptor_tmp->non_blocking_send = true;
             descriptor = descriptor_tmp;

             server_locator.kind = LOCATOR_KIND_TCPv4;
diff --git a/examples/cpp/discovery_server/ClientSubscriberApp.cpp b/examples/cpp/discovery_server/ClientSubscriberApp.cpp
index a026455eb..46f3a7c65 100644
--- a/examples/cpp/discovery_server/ClientSubscriberApp.cpp
+++ b/examples/cpp/discovery_server/ClientSubscriberApp.cpp
@@ -117,6 +117,7 @@ ClientSubscriberApp::ClientSubscriberApp(
             // descriptor_tmp->interfaceWhiteList.push_back(ip_server_address);
             // One listening port must be added either in the pub or the sub
             descriptor_tmp->add_listener_port(0);
+            descriptor_tmp->non_blocking_send = true;
             descriptor = descriptor_tmp;

             server_locator.kind = LOCATOR_KIND_TCPv4;
diff --git a/examples/cpp/discovery_server/ServerApp.cpp b/examples/cpp/discovery_server/ServerApp.cpp
index 04e10d1e1..403f8f4b7 100644
--- a/examples/cpp/discovery_server/ServerApp.cpp
+++ b/examples/cpp/discovery_server/ServerApp.cpp
@@ -121,6 +121,7 @@ ServerApp::ServerApp(
         {
             auto descriptor_tmp = std::make_shared<eprosima::fastdds::rtps::TCPv4TransportDescriptor>();
             descriptor_tmp->add_listener_port(config.listening_port);
+            descriptor_tmp->non_blocking_send = true;
             descriptor = descriptor_tmp;

             listening_locator.kind = LOCATOR_KIND_TCPv4;
```

**Comment by chunyisong** [comment]
Hi @cferreiragonz , thank you for your response.
I tested the issue with 'non_blocking_send = true' and it seems working properly.But I have a few questions:

1.  We want to transfer more datas without data lose and to be notified (such as return value or callback function) if data lose,so the issue test with '--reliable --transport tcpv4' options. So  with 'non_blocking_send = true'  option we get no notification and as far as I know may not be able to address the issue of data loss. Welcom to suggest any ways to handle the issue.
2.  **_'This causes the socket queues to grow until they reach their maximum size'_**.Can you tell me specifically which dds or system config option the 'socket queues' refers to? I want to check and chang the option to observe effect.

**Comment by cferreiragonz** [comment]
Hi @chunyisong. I am glad to hear you managed to make the test work with the `non_blocking_send=true` option.
Regarding your questions:

1. Since your Data Writers are configured as reliable, any message discarded due to the `non_blocking_send` will be resent  when the reader notifies the writer that it has not received the sample. In the end, the behavior will be the same as if the sample was lost during network transmission, so no messages should be lost. Just be sure to properly configure the [History](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/standardQosPolicies.html#historyqospolicy) of the Data Writer to prevent overwriting samples that might need to be resent.
2. For increasing the send and receive buffer sizes, please refer to our [documentation](https://fast-dds.docs.eprosima.com/en/latest/fastdds/use_cases/large_data/large_data.html#increasing-socket-buffers-size). You will have to configure **both** the **DDS application** and **your system**. Keep in mind that increasing the send and receive buffer size will only delay the block if the message writing rate remains unchanged. You can directly configure the buffer sizes in the example you were using similarly to the `non_blocking_send` option:
```cpp
descriptor_tmp->receiveBufferSize = 1000000;
descriptor_tmp->sendBufferSize = 1000000;
```
Remember to adjust the system maximum values as specified in the docs.

**Comment by chunyisong** [comment]
Hi @cferreiragonz .Thank you for your reply and suggestion.I will try the options.

**Comment by cferreiragonz** [comment]
You're welcome, @chunyisong. I am closing this issue for now, as there isn't any bug in the Discovery Server. If you have any further questions or concerns, please feel free to ask in our [Discussion Forums](https://github.com/eProsima/Fast-DDS/discussions), and we will be happy to assist you.

Additionally, if you are interested in more personalized support, you can consider reaching out to our [Commercial Support](https://github.com/eProsima/Fast-DDS#getting-help) team.
