### ISSUE TITLE
Working with multiple Ethernet ports [5687]

### ISSUE THREAD

**Issue by i-and** [eProsima/Fast-DDS#538]
I have a PC with two Ethernet ports that are connected into one switch. I want to send/receive traffic that exceeds the bandwidth of one port, but less than the bandwidth of two ports. 

1. How in Fast-RTPS within one application to bind each DataReader to a specific Ethernet port, so as to explicitly redistribute incoming traffic on the ports?
2. What is the situation with the ability to bind outgoing traffic (DataWriters)?

**Comment by IkerLuengo** [comment]
Hi @i-and,

If I understand correctly, you are trying to balance the communication between publisher and subscriber through two different Ethernet interfaces, because a single interface does not have enough bandwidth to handle the data. The following answer assumes this scenario.

First of all, Fast-DDS does not provide a mechanism to perform load balancing between two network interfaces for a single pair of DataWriter/DataReader. If there are several interfaces available to communicate a DataWriter and a DataReader, the data will be sent through one of them, but not automatically balanced. Therefore, all the balancing mechanism must be implemented at user level, using two separate pairs of DataWriter/DataReader, one pair handling half of the data flow and the other one handling the other half. How to distribute the load on the publishing side and how to recombine the data on the subscribing side is up to the application. A very naïve (but effective in most situations) approach is to alternatively send one data sample through each DataWriter, and then consume the data from both DataReaders. If message order needs to be kept, the [source timestamp](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/subscriber/sampleInfo/sampleInfo.html#dds-layer-subscriber-sampleinfo-sourcetimestamp) can be used to assert the ordering, or a sequence number can be added to the payload.

Then we have the issue of attaching each DataWriter/DataReader to a single interface. [Fast-DDS Documentation](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/whitelist.html) explains how to use interface whitelists to limit the network interfaces a DomainParticipant can use. The whitelist basically specifies the IP address(es) of the interface(s) the DomainParticipant is allowed to use. Therefore:

On the Publisher side, create DomainParticipant1 attached to Interface1, with DataWriter1, and DomainParticipant2 attached to Interface2, with DataWriter2
On the Subscriber side, create DomainParticipant3 attached to Interface1, with DataReader1, and DomainParticipant4 attached to Interface2, with DataReader2

In order to avoid unnecessary meta-traffic communication between Participants 1-4 and Participants 2-3, we can go one step further and create DomainParticipant1 and DomainParticipant3 with one [DomainID](https://fast-dds.docs.eprosima.com/en/latest/fastdds/api_reference/dds_pim/domain/domainparticipantfactory.html#_CPPv4N8eprosima7fastdds3dds24DomainParticipantFactory18create_participantE10DomainId_tRK20DomainParticipantQosP25DomainParticipantListenerRK10StatusMask) and DomainParticipant2 and DomainParticipant3 with another DomainID, effectively making the participants on different domains invisible to each other.

Hope this helps clarifying your doubts. Please, feel free to reopen the issue if you have any more questions.
