### ISSUE TITLE
Can`t create DataWriter*(Publisher::create_datawriter(...)) from DataReaderListener::on_data_available(DataReader* reader) [8621]

### ISSUE THREAD

**Issue by kwisp** [eProsima/Fast-DDS#849]
When I do this, program is hanging on  function create_datawriter(...). strace shows inf nanosleep(...) call.

**Comment by jparisu** [comment]
This error comes from using incorrectly the listener thread.
https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/entity/entity.html#listener
updated here: https://github.com/eProsima/Fast-RTPS-docs/pull/190

In this case, creating a new DataWriter in SharedMemory (from the same process - https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/shared_memory/shared_memory.html) will trigger a blockade of the process with itself.

To avoid this problem, the function `wait_for_unread_message` from the `DataReader` could be use instead of the listener callback `on_data_available`, and there you can create and destroy new entities.

If you have further questions regarding this issue, please send us the code you are trying to execute and we could support you with more accurate feedback.
