### ISSUE TITLE
Domain::registerType with data structure created on stack [8623]

### ISSUE THREAD

**Issue by gladijos** [eProsima/Fast-DDS#850]
TopicAttributes copy constructor copy pointers on name and dataType. If I call Domain::registerType with second argument that created on stack and after this make publisher with this participant and try to publish smthing I'll see "pure virtual function call". Why I should store data instance if participant really is needed only by data type name?

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @gladijos,

The participant not only needs the data type name, but it also needs to know the TopicDataType, a specialized class for each specific type that will be used by the application. This class provides the participant with the methods to serialize and deserialize a specific data type. In order for the participant's publisher to publish, the participant should know the data type that is being written and, similarly, in order for the subscriber to read a sample, the same is required. In fact, the Domain::registerType method has a TODO comment (in spanish) saying that it should be better to use an internal TopicDataType object instead of the one provided by the user, just in case that the user deletes this object beforehand, which is the same case that you ask about.

However, a new API has been released recently so the API that you refer to is being deprecated. If you want to keep using this API you should register your TopicDataType object and ensure that the object is not deleted during the scope of your application.

For more information, here you have the links to the Fast DDS documentation:
[Definition of data types](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/topic/typeSupport/typeSupport.html)
[TopicDataType](https://fast-dds.docs.eprosima.com/en/latest/fastdds/api_reference/dds_pim/topic/topicdatatype.html#_CPPv4N8eprosima7fastdds3dds13TopicDataTypeE)

I'll go ahead and close this issue considering the question to have been answered. However, feel free to comment or reopen at any time if you need further information.
